### ISSUE TITLE
cant find engine-components

### ISSUE THREAD

**Issue by huihui-gao** [needle-tools/needle-engine-support#102]
when i click Export Info  component's Play ,show a error "Projects/CollaborativeSandbox/node_modules/@needle-tools/engine/engine-components/codegen does not exist" 
this is 
![image](https://user-images.githubusercontent.com/69502543/199636886-cac4cbd0-34cc-4759-b537-7e507c903984.png)

**Comment by marwie** [comment]
Hello, looks like the it is right - i dont see the ``engine-components`` directory in your screenshot.
Please try clicking ``Clean Install`` on the ExportInfo component (hold ALT while hovering the Install button)
