### ISSUE TITLE
VR light intensity 

### ISSUE THREAD

**Issue by 3inary** [needle-tools/needle-engine-support#103]
To reproduce you can check any needle scene with lights in VR.
The lights are way dimmer, almost off, then in the browser or AR views.

**Comment by marwie** [comment]
The problem seems to be exclusive to the Sandbox template

**Comment by marwie** [comment]
Found the issue: the light intensity was scaled when part of an ``WebARSessionRoot`` component (they applied the scale of the session so they would be consistently bright when e.g. viewed in miniature AR) - this shouldnt happen in VR tho. Will be fixed in the next update

**Comment by marwie** [comment]
Please try version 2.43.0-pre

**Comment by 3inary** [comment]
That solved it.
