### ISSUE TITLE
Error: THREE.EXRLoader: provided file doesn't appear to be in OpenEXR format.

### ISSUE THREAD

**Issue by hapqe** [needle-tools/needle-engine-support#104]
After baking the lighting in Unity I get the following Error: _**THREE.EXRLoader: provided file doesn't appear to be in OpenEXR format.**_ 

I am unsure if baking is the specific reason, doing so however consistently reprocuses this Error.

![image](https://user-images.githubusercontent.com/66736985/200414699-a8534973-c61f-4c95-9592-39cee6af6935.png)

Unity: 2021.3.8f1, using URP
Platform: Windows 10

Any Ideas?

**Comment by marwie** [comment]
Hello, can you please check that your project lightmaps are set to normal quality?

**Comment by hapqe** [comment]
They weren't, assuming you meant the lightmap compression on the lightingdata asset.
![image](https://user-images.githubusercontent.com/66736985/200426167-725eb6fa-1f56-4110-b6f8-008e4d80cefa.png)
I now changed it to normal quality, however I still get the same error loading the page.

**Comment by marwie** [comment]
I mean the settings in the Player settings

https://engine.needle.tools/docs/export.html#custom-shaders

**Comment by hapqe** [comment]
I must have missed that step in the guide, everything works now.
Thanks!

**Comment by marwie** [comment]
Great! 🙂
