### ISSUE TITLE
Camera Layermask affects object rendering

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#105]
Using Unity 2022.1.20f1 and Windows 11
In the example scene here, if you build with Exporter 2.39.3-pre, it builds fine, roll up to any version of Exporter above and you will find that the hotspots in the scene don't export. On builds with 2.41.0-pre and above, you will see some spam of Vite connected logs like below and parts of the scene don't render 

![image](https://user-images.githubusercontent.com/10745594/201064021-76127f1b-e389-4b26-8885-613c24e8e4d0.png)

With 2.39.3-pre
![image](https://user-images.githubusercontent.com/10745594/201064675-e200d404-82ad-4bdc-aa70-699623a2ed40.png)

With 2.41.0-pre
![image](https://user-images.githubusercontent.com/10745594/201066043-f92f2e97-3e75-45b6-b1b5-c91710049351.png)

Repro project:
[newProject-221110_uw.zip](https://github.com/needle-tools/needle-engine-support/files/9979738/newProject-221110_uw.zip)

**Comment by ROBYER1** [comment]
There are also no errors or warnings in that borked build from 2.41.0-pre

**Comment by marwie** [comment]
Thanks for the report. The reason is the camera being set to the Hotspot layer and previously layer assignment from Unity wasnt handled properly.

I dont think we want to override the layer for the camera object using the layermask from Unity here. In the meantime you can change the layer back to default

**Comment by marwie** [comment]
Will be fixed in the next version as well as assign the culling mask settings from Unity instead 😊

**Comment by marwie** [comment]
Published the update earlier today!
