### ISSUE TITLE
Canvas set active by animation doesn't render images - used to work in 2.39.3-pre

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#106]
Using Unity 2022.1.20f1, Exporter 2.46.0-pre and Windows 11, this used to work in 2.39.3-pre Exporter. Tested with local server runs from the Editor in Chrome.

Use this test project to see the issue, please focus on just the 'X' in a circle close button not showing in local server runs, this is circled in red/orange in the screenshots below. The main image in the panel that pops up is excluded from the sample project as it contains project sensitive information, so please don't worry about the panel not showing what is scribbled over, that does show, it's just the X close button not showing which is in a canvas.

Test proj:
[newProject-221114_uw.zip](https://github.com/needle-tools/needle-engine-support/files/10004247/newProject-221114_uw.zip)

Using 2.39.3-pre:
![image](https://user-images.githubusercontent.com/10745594/201694225-c4cab222-3605-444d-9d2b-e7e51af9eea6.png)

Using 2.46.0-pre:
![image](https://user-images.githubusercontent.com/10745594/201693949-92c57de8-0425-4b74-aabf-7b95d7d39ae6.png)

**Comment by marwie** [comment]
Latest version should've fixed this
