### ISSUE TITLE
Stencil Rendering doesn't work in AR-Mode in newer Versions (Still works on 2.39.2-pre)

### ISSUE THREAD

**Issue by trytomatie** [needle-tools/needle-engine-support#107]
Using unity 2021.3.11f
Tested with https://github.com/needle-tools/needle-engine-samples on the portal Stencil Portal Project
![Screenshot_20221115-121934_Chrome](https://user-images.githubusercontent.com/25536643/201907214-3a802341-15e4-4bfd-807e-8dd8b8d84ad7.jpg)

**Comment by marwie** [comment]
Thanks for reporting! Will look into it
