### ISSUE TITLE
env: node: No such file or directory

### ISSUE THREAD

**Issue by hananbeer** [needle-tools/needle-engine-support#108]
I'm trying to install needle tools on my macOS 13, unity 2022.1.22f1.

I have imported needle tools 2.45.0. initially threejs was missing so I had to install it from command line.

once I try to click install in the Export Info component I get the following error:
env: node: No such file or directory

I set Project Folder path to:
Projects/sand
which I also created from command line because it was missing. I think it has something to do with this path, I'm not sure which path it should refer to.?

**Comment by hananbeer** [comment]
which npm:
`/opt/homebrew/opt/node@16/bin/npm`

strangely enough after setting the path manually while I still get those errors, I could run `npm start` in the project folder and it worked. I still get many errors in the UI even when I start, probably because some path is wrong, but it does run.

on top of console errors I also see this:
<img width="490" alt="image" src="https://user-images.githubusercontent.com/63053861/202118182-7c2ac99e-dbcf-467f-8291-cf1e064e388a.png">

**Comment by marwie** [comment]
Thanks for the info. 

I think you must not include the ``npm`` folder in the path. Could you try entering ``/opt/homebrew/opt/node@16/bin`` as path? You might need to restart Unity after changing that.

For comparison these are used by default for osx:

```
"/usr/local/bin/",
"/usr/bin",
"/bin",
"/usr/sbin",
"/sbin",
"/opt/homebrew/bin"
```

Also what I notice is that the ExportInfo component says "(local)" at the bottom after the versions. You installed the package using the package installer right?

**Comment by marwie** [comment]
Yes i meant npm paths (the paths at the top shouldnt be necessary to change)

**Comment by marwie** [comment]
Hello @hananbeer did you solve the problem or does it still persist?

**Comment by marwie** [comment]
Closing since no further info was provided
2.53.1 did also add some fixed and improvements for OSX, especially around using node when installed by nvm
