### ISSUE TITLE
Canvas textures (UI Sprites) get exported with wrong color space in production builds

### ISSUE THREAD

**Issue by hybridherbst** [needle-tools/needle-engine-support#109]
Using the same texture in `Canvas > Image` and on a quad with an `Unlit` material results in the UI Image becoming darker after texture compression: 

In the following screenshots, the background uses a UI Image, the foreground uses an Unlit quad, with the same texture.

**npm run start (uncompressed)**
![image](https://user-images.githubusercontent.com/2693840/202458669-ebb16671-244e-4b8f-96dd-84732e9c9e86.png)

**npm run serve (compressed)**
![image](https://user-images.githubusercontent.com/2693840/202458849-5fae5b0c-1e9d-416e-bc2a-1f05a7db84fc.png)

**Comment by marwie** [comment]
Exported textures look identical in gltf report (left normal texture used on quad with unlit material, right sprite texture assigned to image component)

![image](https://user-images.githubusercontent.com/5083203/206158479-8dfa230b-23d2-4150-a243-d42a91160f4e.png)

It reproduces in production builds. When setting the encoding to LINEAR on the UI texture / sprite it matches the texture but it will then look wrong when being used on e.g. another object:

![image](https://user-images.githubusercontent.com/5083203/206159006-f3002bd9-e9ec-4651-a5c7-02e96ea9ae64.png)

**Comment by marwie** [comment]
Should be fixed in 2.53.x-pre
