### ISSUE TITLE
AR bug - Skinned Mesh Renderer in scene is showing up huge in the AR view before placing content with the viewing circle

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#11]
This is reproducible with the project I sent Marcel privately, when you deploy to glitch and load on a phone then press view in AR, the animated model in the scene I added is showing up huge in the AR view in the middle of the space, the placement circle pointer is there though too. Once you tap on the pointer circle to place the scene, the huge version of the animated model disappears.

Hopefully this is enough to repro, I will share a glitch url privately with Marcel for this too to see what we are seeing our end

**Comment by marwie** [comment]
Thanks for reporting! 
Is the model a child of an WebARSessionRoot ?

**Comment by marwie** [comment]
You could also just put a WebARSessionRoot on SceneRoot I think. I just checked your url and it looks like this is the issue here. We currently only hide the WebARSessionRoot content on placement
