### ISSUE TITLE
toktx not found but installed

### ISSUE THREAD

**Issue by Podden** [needle-tools/needle-engine-support#112]
Needle fails to find the toktx installation of mine. Default toktx will install on my machine on "C:\Program Files" instead on "C:\Program Files (x86)".

My Path Variable is correctly set:
![grafik](https://user-images.githubusercontent.com/3932988/203100586-58b05a29-8c11-4d38-ae38-4d404cc9f933.png)

The generated call in HasMinimumToktxVersionInstalled() generates an error on my machine
![grafik](https://user-images.githubusercontent.com/3932988/203100707-1ec602bc-53ce-4ff9-8f5a-362cc4522404.png)

The Function itself generates another message
![grafik](https://user-images.githubusercontent.com/3932988/203100980-b80ea6e4-8d61-4b93-96f4-36bdf0e28ec7.png)

Normal version Call gets through normally
![grafik](https://user-images.githubusercontent.com/3932988/203101102-a24fe725-8896-436f-b138-c7eed11e790b.png)

I'm on Windows 10 Enterprise x64

**Comment by Podden** [comment]
Unity yes, but computer no. That helped, thx :)

**Comment by krisrok** [comment]
Same problem. But interestingly, it works without a reboot when the call has the file extension added: "toktx.exe" :D I've yet to try the reboot.

I can also confirm the path @Podden mentiones is the right one: The program installs to %programfiles% and not %programfiles(x86)% anymore. This should be changed if there is the path-setting command still has reason to exist.
