### ISSUE TITLE
Curl error 60: Cert verify failed: UNITYTLS_X509VERIFY_FLAG_USER_ERROR1

### ISSUE THREAD

**Issue by hquu** [needle-tools/needle-engine-support#114]
Curl error 60: Cert verify failed: UNITYTLS_X509VERIFY_FLAG_USER_ERROR1
i have this

**Comment by marwie** [comment]
Hello, could you please provide more context to this?

- Unity version
- Needle Exporter version
- When does the bug happen?
- Can you reproduce it? If yes how
