### ISSUE TITLE
Shadow Acne with Collaborative Sandbox Sample Scene on iOS iPhone 6 Mozilla WebXR Viewer

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#116]
### Describe the bug 💬

The collaborative sandbox sample scene from the samples repo has shadow acne on iPhone 6 with Mozilla WebXR Viewer. Cannot repro it on Android Xperia 1 Chrome or Desktop Windows 11 chrome
![IMG_0038](https://user-images.githubusercontent.com/10745594/203793609-576de73f-eb81-4eba-b303-66469b3838b2.PNG)

### Operating System 👩‍💻

iOS (mobile)

### What browsers are you seeing the problem on? 🏄‍♂️

Mozilla XR

### Editor Version 🎲

2022.x

### Needle Exporter version

2.49.0-pre

### Project Info (Unity only) 📜

```json
{
  "ExportInfoGameObjectName": "Export",
  "ExportInfoGameObjectIsEnabled": true,
  "UnityProjectPath": "C:/Unity_Projects/NeedleEngineSamples/projects/Needle Engine Samples 2020_3/Assets",
  "UnityVersion": "2022.1.20f1",
  "SceneName": "Sandbox",
  "ProjectPath": "Library/Needle/Sample",
  "ProjectDirectoryExists": true,
  "ProjectIsInstalled": true,
  "NeedleEngineInstalled": true,
  "HasNodeInstalled": true,
  "HasTokTxInstalled": true,
  "HasMinimumToktxVersionInstalled": false,
  "RenderPipeline": "UniversalRenderPipelineAssetStencil (UnityEngine.Rendering.Universal.UniversalRenderPipelineAsset)",
  "GzipEnabled": false,
  "NeedleEngineExporterVersion": "2.49.0-pre",
  "NeedleEngineVersion": "2.49.0-pre",
  "NeedleEngineExporterPath": "Packages/com.needle.engine-exporter/package.json",
  "NeedleEnginePath": "Packages/com.needle.engine/package.json",
  "FileStats": "By Type:\r\n•\t.glb →  x 2 = 1.4 mb\r\n•\t<b>Total = 1.4 mb</b>\r\n----\r\nBy Directory:\r\n•\tassets →  x 2 = 1.4 mb\r\n",
  "NeedleComponentsInScene": [
    "Needle.Engine.ExportInfo",
    "Needle.Engine.Codegen.ComponentGenerator",
    "Needle.Engine.Deployment.DeployToGlitch",
    "Needle.Engine.Shaders.SkyboxExportSettings",
    "Needle.Engine.Components.GltfObject",
    "Needle.Engine.Components.SyncedRoom",
    "Needle.Engine.Components.Networking",
    "Needle.Engine.Components.WebXR",
    "Needle.Engine.Components.WebXRSync",
    "Needle.Engine.Components.SpectatorCamera",
    "Needle.Engine.Components.SyncedCamera",
    "Needle.Engine.Components.AvatarBlink_Simple",
    "Needle.Engine.Components.PlayerColor",
    "Needle.Engine.Components.WebARSessionRoot",
    "Needle.Engine.Components.ObjectRaycaster",
    "Needle.Engine.Components.TeleportTarget",
    "Needle.Engine.Components.XRRig",
    "Needle.Engine.Components.OrbitControls",
    "Needle.Engine.Components.XRFlag",
    "Needle.Engine.Components.Deletable",
    "Needle.Engine.Components.SyncedTransform",
    "Needle.Engine.Components.DragControls",
    "Needle.Engine.Components.DeleteBox",
    "Needle.Engine.Components.BoxGizmo",
    "Needle.Engine.Components.Duplicatable"
  ],
  "TypeCacheIsDirty": true,
  "TypeScriptTypes": []
}
```

### Steps to reproduce 🔢

```bash
1. Open Sample scene of Collaborative Sandbox in Unity 2022.1.20f1
2. Run local server
3. Open on iOS on iPhone 6 in Mozilla WebXR Viewer
```

### Reproduction ♻

Sample glitch site: https://wiry-bald-revolve.glitch.me/

Sample proj: [Sample-221124_uw.zip](https://github.com/needle-tools/needle-engine-support/files/10084870/Sample-221124_uw.zip)

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ROBYER1** [comment]
Could be related to iOS floating point precision?
https://stackoverflow.com/questions/50945270/threejs-shadow-artifact-ios-devices

**Comment by marwie** [comment]
Is this still an issue using the latest version?

**Comment by ROBYER1** [comment]
> 

Confirmed this is fixed! What did you change?

**Comment by marwie** [comment]
Nothing specific to Mozilla XR but the default shadow settings are now handled better on export / trying to map them to better threejs values (Unity shadow settings work differently than in three and then it also depends on URP <> builtin and URP with AdditionalLightData and without...)

Also removed code that tried to be smart about those values at runtime in the Light component - altough I dont know how that should have only affected one platform.
