### ISSUE TITLE
ParticleSystemModules.ts(1074,13): error TS7030: Not all code paths return a value.

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#119]
### Describe the bug 💬

When trying to build prod/dev to Glitch or local dist with the attached project, I keep getting this error blocking it:

```
../../NeedleWebDemos_BugReport/Library/PackageCache/com.needle.engine@2.49.0-pre/package~/engine-components/ParticleSystemModules.ts(1074,13): error TS7030: Not all code paths return a value.
Open C:\Users\Robert.Farthing\Downloads\ARDemo-221125_uw\project\ARDemo/../../NeedleWebDemos_BugReport/Library/PackageCache/com.needle.engine@2.49.0-pre/package~/engine-components/ParticleSystemModules.ts

```

This is the same proj as https://github.com/needle-tools/needle-engine-support/issues/118 and I hit this error when I tried to build the project and deploy it to Glitch for that issue.

### Operating System 👩‍💻

Windows

### What browsers are you seeing the problem on? 🏄‍♂️

Chrome

### Editor Version 🎲

2022.x

### Needle Exporter version

2.49.0-pre

### Project Info (Unity only) 📜

```json
{
  "ExportInfoGameObjectName": "Export Info",
  "ExportInfoGameObjectIsEnabled": true,
  "UnityProjectPath": "C:/Users/Robert.Farthing/Downloads/ARDemo-221125_uw/NeedleWebDemos_BugReport/Assets",
  "UnityVersion": "2022.1.23f1",
  "SceneName": "ARDemo",
  "ProjectPath": "../project/ARDemo",
  "ProjectDirectoryExists": true,
  "ProjectIsInstalled": true,
  "NeedleEngineInstalled": true,
  "HasNodeInstalled": true,
  "HasTokTxInstalled": true,
  "HasMinimumToktxVersionInstalled": false,
  "RenderPipeline": "UniversalRenderPipelineAsset (UnityEngine.Rendering.Universal.UniversalRenderPipelineAsset)",
  "GzipEnabled": false,
  "NeedleEngineExporterVersion": "2.49.0-pre",
  "NeedleEngineVersion": "2.49.0-pre",
  "NeedleEngineExporterPath": "Packages/com.needle.engine-exporter/package.json",
  "NeedleEnginePath": "Packages/com.needle.engine/package.json",
  "FileStats": "By Type:\r\n•\t.glb →  x 2 = 0.7 mb\r\n•\t<b>Total = 0.7 mb</b>\r\n----\r\nBy Directory:\r\n•\tassets →  x 2 = 0.7 mb\r\n",
  "NeedleComponentsInScene": [
    "Needle.Engine.ExportInfo",
    "Needle.Engine.Codegen.ComponentGenerator",
    "Needle.Engine.Deployment.DeployToGlitch",
    "Needle.Engine.Components.GltfObject",
    "Needle.Engine.Components.WebARSessionRoot",
    "Needle.Engine.Components.TeleportTarget",
    "Needle.Engine.Components.ObjectRaycaster",
    "Needle.Engine.AdditionalData.LightShadowData",
    "Needle.Engine.Components.WebXR",
    "Needle.Engine.Components.WebXRSync",
    "Needle.Engine.Components.OrbitControls",
    "Needle.Engine.AdditionalData.CameraARData",
    "Needle.Typescript.GeneratedComponents.AlignHeightToGround",
    "Needle.Typescript.GeneratedComponents.ARControls"
  ],
  "TypeCacheIsDirty": false,
  "TypeScriptTypes": []
}
```

### Steps to reproduce 🔢

```bash
1. Open Project in Unity 2022.1.23f1
2. Try to Deploy dev/prod to glitch or try to build dev/prod local builds
3. See error
```

### Reproduction ♻

Repro proj:
[ARDemo-221125_uw.zip](https://github.com/needle-tools/needle-engine-support/files/10093043/ARDemo-221125_uw.zip)

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marwie** [comment]
Just out of curiousity since we deployed with this version to glitch multiple times: is this using a custom project template? Did you possibly modify the tsconfig?`

**Comment by ROBYER1** [comment]
It is a custom project template but only for the purpose of adding mkcert plugin for simple AR testing on iOS so I wonder what is causing that template to cause a ParticleSystem.ts error :(

**Comment by marwie** [comment]
tsconfig has strict set to false instead of true
Setting it to true throws a bunch of errors from your scripts
When i remove those scripts it builds fine
Very odd - to my understanding strict true should highlight those errors (as it does with the scripts in the project).

**Comment by ROBYER1** [comment]
Also unusual that hitting play causes the project to run in the local browser just fine on local server. If there is any further investigation for me to do let me know as if it is a script of mine silently causing errors I will check that by changing strict back to true for now.

**Comment by marwie** [comment]
Yes please try enabling strict mode - i'll see if I can make it throw the error with the default tsconfig too tho and/or try to figure out why it's not catching that here

**Comment by ROBYER1** [comment]
Will do, is most confusing when the build runs fone in local server but building a dev dist or prod dist fails

**Comment by marwie** [comment]
Yes agreed - that error will be fixed in the next update
