### ISSUE TITLE
msilib OSX Blender

### ISSUE THREAD

**Issue by klich3** [needle-tools/needle-engine-support#123]
### Describe the bug 💬

Hi there,

Installing the addon on any Blender on OSX I have this error:

```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.4/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/Users/too-m/Library/Application Support/Blender/3.4/scripts/addons/Needle Engine Exporter for Blender/__init__.py", line 13, in <module>
    from .panels_project import NeedleComponents
  File "/Users/too-m/Library/Application Support/Blender/3.4/scripts/addons/Needle Engine Exporter for Blender/panels_project.py", line 6, in <module>
    from msilib.schema import Icon
ModuleNotFoundError: No module named 'msilib'
```

**Solution:** 
Removing un-used moddule 

`from msilib.schema import Icon` on line 6 in file `../Library/Application Support/Blender/3.4/scripts/addons/Needle Engine Exporter for Blender/panels_project.py`

### Operating System 👩‍💻

macOS

### What browsers are you seeing the problem on? 🏄‍♂️

Chrome

### Editor Version 🎲

2020.3

### Needle Exporter version

.

### Project Info (Unity only) 📜

```json
.
```

### Steps to reproduce 🔢

```bash
1. Open Blender
2. Plugins 
3. Install
```

### Reproduction ♻

.

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marwie** [comment]
hi, we dont support the blender addon on OSX or Linux yet. its windows only during closed alpha

**Comment by marwie** [comment]
@klich3 @chicortiz 
could you try if 0.15.1 works for you on OSX / linux now?

**Comment by marwie** [comment]
This has been fixed
