### ISSUE TITLE
Docs search for methods returns no results

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#125]
### Describe the bug 💬

Search for something like createAR in the docs and it returns nothing, makes the search feature difficult to use for finding functions or methods

### Operating System 👩‍💻

Windows

### What browsers are you seeing the problem on? 🏄‍♂️

Firefox, Chrome, Safari, Microsoft Edge

### Editor Version 🎲

2020.3

### Needle Exporter version

-

### Project Info (Unity only) 📜

```json
-
```

### Steps to reproduce 🔢

```bash
-
```

### Reproduction ♻

Go to the link below, search for a method or code mentioned in the docs like 'MyComponent ' from this page:
https://engine.needle.tools/docs/scripting-examples.html

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marwie** [comment]
Hi @ROBYER1 this should now be improved

Regarding your example ``createAR`` does actually not exist in the docs anywhere
