### ISSUE TITLE
Particle World Space mode uses a different rotation conversation than Unity

### ISSUE THREAD

**Issue by Podden** [needle-tools/needle-engine-support#126]
### Describe the bug 💬

Setting Particle to Worldspace in combination with Box Emitter seems to use a wrong coordinate conversation.

### Operating System 👩‍💻

Windows

### What browsers are you seeing the problem on? 🏄‍♂️

Firefox

### Editor Version 🎲

2021.3

### Needle Exporter version

2.62.0-pre

### Steps to reproduce 🔢

```bash
To reproduce:
Create Particle System, set to Box Emitter and "Simulation Space" to "World Space" then rotate Transform around 90° and compare Unity and Needle Build
```

### Reproduction ♻

Editor
![grafik](https://user-images.githubusercontent.com/3932988/219112450-3588427d-61fb-4799-8614-48d3e1fe8dab.png)
Debug Build
![grafik](https://user-images.githubusercontent.com/3932988/219112544-9fca8a3d-b297-4be6-9f0c-f92d5703d227.png)

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Podden** [comment]
Definitely something weird happening

Editor
https://user-images.githubusercontent.com/3932988/219422202-224e478a-e5a7-43ea-99ef-de4081389a36.mp4
Build
https://user-images.githubusercontent.com/3932988/219422191-12355dbe-6e45-4fad-8e5f-4db988818552.mp4
Settings
![grafik](https://user-images.githubusercontent.com/3932988/219422093-f6c6ed09-d97d-454c-b8c3-798135fc7086.png)

**Comment by Podden** [comment]
Found it! :)

change ParticleSystemModules.ts Line 539 from
`            this._worldSpaceMatrixInverse.copy(this._worldSpaceMatrix).invert();`
to
`            this._worldSpaceMatrixInverse.copy(this._worldSpaceMatrix);`

**Comment by marwie** [comment]
Hi @Podden can you try this with the latest version if it's fixed?

**Comment by Podden** [comment]
Fixed, thx!
