### ISSUE TITLE
Blender Plugin version 0.15.0 not working on Ubuntu 22.04.1

### ISSUE THREAD

**Issue by chicortiz** [needle-tools/needle-engine-support#127]
### Describe the bug 💬

Hi Guys.

When I select the .zip folder everything is OK, I can find the Plugin inside the "User" tab. The problem is when I click the checkbox to activate the plugin. (The one that says "Export: Needle Engine Exporter for Blender").

I get the following error no matter if I use Blender 3.4.1 or Blender 3.3.1:

##############

ortiz@desk:~/Downloads/blender-3.4.1-linux-x64$ ./blender
Read prefs: /home/ortiz/.config/blender/3.4/config/userpref.blend
Traceback (most recent call last):
  File "/home/ortiz/Downloads/blender-3.4.1-linux-x64/3.4/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "/home/ortiz/.config/blender/3.4/scripts/addons/Needle Engine Exporter for Blender/__init__.py", line 13, in <module>
    from .panels_project import NeedleComponents
  File "/home/ortiz/.config/blender/3.4/scripts/addons/Needle Engine Exporter for Blender/panels_project.py", line 6, in <module>
    from msilib.schema import Icon
ModuleNotFoundError: No module named 'msilib'

###############

Greetings,

Ortiz

### Operating System 👩‍💻

Linux

### Editor Version 🎲

2020.3

### Needle Exporter version

0.15.0

### Steps to reproduce 🔢

```bash
1.
2.
3.
...
```

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marwie** [comment]
Hello, thanks for reporting. Right now (during pre-alpha) the addon is only tested on windows (as described in the docs)

**Comment by hybridherbst** [comment]
Still thanks for the feedback! :) 

Related
- https://github.com/needle-tools/needle-engine-support/issues/123

**Comment by chicortiz** [comment]
Thank you very much for pointing out Marcel!
Thank you also @hybridherbst !

**Comment by chicortiz** [comment]
> Related
> 
>     * [msilib OSX Blender #123](https://github.com/needle-tools/needle-engine-support/issues/123)

The related link solves the issue/bug :)

**Comment by marwie** [comment]
Thanks for the info!
