### ISSUE TITLE
Error: Compression reduced vertex count unexpectedly, corrupting morph targets. Applying the "weld" function before compression may resolve the issue.

### ISSUE THREAD

**Issue by faizalski** [needle-tools/needle-engine-support#13]
Trying to compile production build with humanoid animated avatar and were met with the following error message. 

```
error: Compression reduced vertex count unexpectedly, corrupting morph targets. Applying the "weld" function before compression may resolve the issue.
<b>Production build <color=#ff2222>failed</color></b>, check the console for errors
UnityEngine.Debug:Log (object)
Needle.Engine.MenuItems/<InternalBuildTask>d__23:MoveNext () (at Library/PackageCache/com.needle.engine-exporter@2.10.0-pre/Core/Editor/MenuItems/MenuItems.cs:283)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder1<bool>:SetResult (bool)
Needle.Engine.Utils.ProcessHelper/<RunCommand>d__0:MoveNext () (at Library/PackageCache/com.needle.engine-exporter@2.10.0-pre/Common/Runtime/Utils/ProcessHelper.cs:225)
UnityEngine.UnitySynchronizationContext:ExecuteTasks ()`
```
Building with Development yields a successful build, but the avatar is upside down and t-posed without animation.
not working as expected. 

Issue communication -> [https://discord.com/channels/717429793926283276/1012484258033573919]

**Comment by hybridherbst** [comment]
For other people running into this:

- we believe this is an upstream issue in gltf-transform or draco with specific meshes
- as a workaround, you should be able to make a Dev deployment instead of a Production deployment, skipping the mesh compression that's causing these issues

We're looking into it!

**Comment by hybridherbst** [comment]
These two both contribute to issue as far as I'm aware:
- https://github.com/google/draco/issues/929
- https://github.com/donmccurdy/glTF-Transform/issues/693
