### ISSUE TITLE
Progressive/Deferred Texture Loading failed if Material has Tiling != 1

### ISSUE THREAD

**Issue by Podden** [needle-tools/needle-engine-support#133]
### Describe the bug 💬

As long as Tiling in materials is 1, everything works fine. But putting tiling eg. on 3, progressive textures do not load.

### Operating System 👩‍💻

Windows

### What browsers are you seeing the problem on? 🏄‍♂️

Firefox, Chrome, Safari

### Editor Version 🎲

2021.3

### Needle Exporter version

2.66.1-pre

### Project Info (Unity only) 📜

```json
{
  "ExportInfoGameObjectName": "Export Info",
  "ExportInfoGameObjectIsEnabled": true,
  "UnityProjectPath": "D:/Projekte/XXXXXXXXXXXX/Assets",
  "UnityVersion": "2021.3.17f1",
  "SceneName": "XXXXXXXXXXXXXX",
  "ProjectPath": "Needle/XXXXXXXXXXX",
  "ProjectDirectoryExists": true,
  "ProjectIsInstalled": true,
  "NeedleEngineInstalled": true,
  "HasNodeInstalled": true,
  "NodeVersion": "v16.16.0",
  "NpmVersion": "8.13.2; npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.",
  "HasTokTxInstalled": true,
  "HasMinimumToktxVersionInstalled": true,
  "RenderPipeline": "MainURPAsset (UnityEngine.Rendering.Universal.UniversalRenderPipelineAsset)",
  "GzipEnabled": false,
  "NeedleEngineExporterVersion": "2.66.1-pre",
  "NeedleEngineVersion": "2.66.1-pre",
  "NeedleEngineExporterPath": "Packages/com.needle.engine-exporter/package.json",
  "NeedleEnginePath": "Packages/com.needle.engine/package.json",
  "FileStats": "By Type:\r\n•\t.glb →  x 4 = 21,8 mb\r\n•\t.json →  x 1 = 0,1 mb\r\n•\t.png →  x 1 = 0,1 mb\r\n•\t.exr →  x 1 = 0,4 mb\r\n•\t.jpg →  x 1 = 0,0 mb\r\n•\t<b>Total = 22,4 mb</b>\r\n----\r\nBy Directory:\r\n•\tassets →  x 8 = 22,4 mb\r\n",
  "NeedleComponentsInScene": [
    "Needle.Engine.Components.GltfObject",
    "Needle.Typescript.GeneratedComponents.NeedleActivateScene",
    "Needle.Typescript.GeneratedComponents.NeedleKeyboardInput",
    "Needle.Engine.AdditionalData.CanvasData",
    "Needle.Typescript.GeneratedComponents.NeedleActivateOverlay",
    "Needle.Typescript.GeneratedComponents.NeedleDeactivateOverlay",
    "Needle.Typescript.GeneratedComponents.NeedleSceneManager",
    "Needle.Engine.ExportInfo",
    "Needle.Engine.Codegen.ComponentGenerator"
  ],
  "TypeCacheIsDirty": false,
  "TypeScriptTypes": []
}
```

### Steps to reproduce 🔢

```bash
- Put Mesh in your scene, add Material with texture (doesn't matter if URP/BRP or Unlit/Lit)
- Add a Texture an set Tiling in Material to something that is not 1
- Activate Progressive Loading in Needle Texture Import Options for this texture or use Progressive Loading Script
- Build scene
- Scene is not loading the high res texture (glb gets correctly exported)
- To check that it's normally working, set tiling to 1, build again, now texture gets correctly loaded progressively
```

### Reproduction ♻

Build which does not work:
https://local.vr-bits.de/tilingtest/?debugprogressive

Project to text on (just vanilla project with a material and a texture with tiling = 3):
 https://local.vr-bits.de/NeedleProgressiveTest.7z

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marwie** [comment]
The update was released today
