### ISSUE TITLE
Rect Transform: Different Pivots in Nested Objects wrong on export

### ISSUE THREAD

**Issue by Podden** [needle-tools/needle-engine-support#134]
### Describe the bug 💬

When I'm eg. exporting a UI Button and setting the parents pivot to (0|0,5) and the child Text stays at Pivot (0.5|0.5), the child moves moves accordingly to the right, which does not happen in Unity Editor
Editor:
![grafik](https://user-images.githubusercontent.com/3932988/226975014-5f737f61-c771-4c91-810c-3eb763a061ba.png)
Build:
![grafik](https://user-images.githubusercontent.com/3932988/226975098-b77108d9-e1fa-4906-912e-166678d2a330.png)

### Operating System 👩‍💻

Windows

### What browsers are you seeing the problem on? 🏄‍♂️

Firefox, Chrome

### Editor Version 🎲

2020.3

### Needle Exporter version

2.66.1-pre

### Project Info (Unity only) 📜

```json
{
  "ExportInfoGameObjectName": "Export Info",
  "ExportInfoGameObjectIsEnabled": true,
  "UnityProjectPath": "D:/Projekte/XXXXXXX/Assets",
  "UnityVersion": "2021.3.17f1",
  "SceneName": "XXXXXXX",
  "ProjectPath": "Needle/XXXXXXX",
  "ProjectDirectoryExists": true,
  "ProjectIsInstalled": true,
  "NeedleEngineInstalled": true,
  "HasNodeInstalled": true,
  "NodeVersion": "v16.16.0",
  "NpmVersion": "8.13.2; npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.",
  "HasTokTxInstalled": true,
  "HasMinimumToktxVersionInstalled": true,
  "RenderPipeline": "MainURPAsset (UnityEngine.Rendering.Universal.UniversalRenderPipelineAsset)",
  "GzipEnabled": false,
  "NeedleEngineExporterVersion": "2.66.1-pre",
  "NeedleEngineVersion": "2.66.1-pre",
  "NeedleEngineExporterPath": "Packages/com.needle.engine-exporter/package.json",
  "NeedleEnginePath": "Packages/com.needle.engine/package.json",
  "FileStats": "By Type:\r\n•\t.json →  x 2 = 0,1 mb\r\n•\t.png →  x 2 = 0,2 mb\r\n•\t.glb →  x 4 = 21,8 mb\r\n•\t.exr →  x 1 = 0,4 mb\r\n•\t.jpg →  x 1 = 0,0 mb\r\n•\t<b>Total = 22,5 mb</b>\r\n----\r\nBy Directory:\r\n•\tassets →  x 10 = 22,5 mb\r\n",
  "NeedleComponentsInScene": [
    "Needle.Engine.Components.GltfObject",
    "Needle.Engine.AdditionalData.CanvasData",
    "Needle.Engine.ExportInfo",
    "Needle.Engine.Codegen.ComponentGenerator",
    "Needle.Typescript.GeneratedComponents.NeedleSceneManager",
    "Needle.Typescript.GeneratedComponents.NeedleActivateScene",
    "Needle.Typescript.GeneratedComponents.NeedleKeyboardInput",
    "Needle.Typescript.GeneratedComponents.NeedleActivateOverlay",
    "Needle.Typescript.GeneratedComponents.NeedleDeactivateOverlay"
  ],
  "TypeCacheIsDirty": false,
  "TypeScriptTypes": []
}
```

### Steps to reproduce 🔢

```bash
- Add Canvas to Needle Scene, set to World Space
- Add a UIButton with Text or some other RectTransform Child
- Export, everything exports fine
- Adjust Pivot of Button Object to 0 | 0.5
- Export, Child(s) of the Button are moved to the side
```

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marwie** [comment]
Hello @Podden can you try 2.67.0-pre if this fixes the issue for you? 

https://github.com/needle-tools/needle-engine-support/releases/tag/release%2F2.67.0-pre

**Comment by Podden** [comment]
I've tested this with 3.6.1 and it works now :). Also thanks for screen space!
