### ISSUE TITLE
Create Bug Report> System.UnauthorizedAccessException: Access to the path 'C:\Users\######USERNAME\AppData\Local\npm-cache\_logs\2023-03-30T13_14_44_333Z-debug-0.log' is denied.

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#139]
### Describe the bug 💬

Since upgrading to 2.67.6-pre I get this error when I use Needle Engine > Report a Bug > Create Bug Report

```
System.UnauthorizedAccessException: Access to the path 'C:\Users\###USERNAME###\AppData\Local\npm-cache\_logs\2023-03-30T13_14_44_333Z-debug-0.log' is denied.
  at System.IO.FileSystem.CopyFile (System.String sourceFullPath, System.String destFullPath, System.Boolean overwrite) [0x00060] in <27586baf39bf4babbfd8a2caabe8e228>:0 
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) [0x00062] in <27586baf39bf4babbfd8a2caabe8e228>:0 
  at Needle.Engine.Problems.ProjectInfoReporter.CopyWebProjectFiles (System.IO.DirectoryInfo webProjectDir, System.IO.DirectoryInfo to, Needle.Engine.Problems.ProjectInfoReporter+CollectionSettings settings) [0x00097] in .\Library\PackageCache\com.needle.engine-exporter@2.67.6-pre\Core\Editor\Problems\Reporting\ProjectInfoReporter.cs:443 
  at Needle.Engine.Problems.ProjectInfoReporter.InternalCollectDebugFiles (System.String header, Needle.Engine.Problems.ProjectInfoReporter+CollectionSettings settings) [0x001a9] in .\Library\PackageCache\com.needle.engine-exporter@2.67.6-pre\Core\Editor\Problems\Reporting\ProjectInfoReporter.cs:134 
```

Is there any reason this is happening? This is a fairly new Needle Project? I stopped the server and right after that the log file deleted itself but the server was running while I tried to export the bug report.

Might be that you need to check if the server is running and stop it first or avoid trying to write to that npm file when exporting a bug report? I tried to delete the file as admin while the server was running but it was locked.

### Operating System 👩‍💻

Windows

### What browsers are you seeing the problem on? 🏄‍♂️

Chrome

### Editor Version 🎲

2022.x

### Needle Exporter version

2.67.6-pre

### Project Info (Unity only) 📜

```json
{
  "ExportInfoGameObjectName": "Export Info",
  "ExportInfoGameObjectIsEnabled": true,
  "UnityProjectPath": "C:/Unity_Projects/EatonInteractive/Assets",
  "UnityVersion": "2022.2.12f1",
  "SceneName": "MainScene",
  "ProjectPath": "Needle/MainScene",
  "ProjectDirectoryExists": true,
  "ProjectIsInstalled": true,
  "NeedleEngineInstalled": true,
  "HasNodeInstalled": true,
  "NodeVersion": "v18.15.0",
  "NpmVersion": "9.6.2",
  "HasTokTxInstalled": true,
  "HasMinimumToktxVersionInstalled": true,
  "RenderPipeline": "URP-HighFidelity (UnityEngine.Rendering.Universal.UniversalRenderPipelineAsset)",
  "GzipEnabled": false,
  "NeedleEngineExporterVersion": "2.67.6-pre",
  "NeedleEngineVersion": "2.67.6-pre",
  "NeedleEngineExporterPath": "Packages/com.needle.engine-exporter/package.json",
  "NeedleEnginePath": "Packages/com.needle.engine/package.json",
  "FileStats": "By Type:\r\n•\t.glb →  x 2 = 54.7 mb\r\n•\t.gltf →  x 2 = 0.0 mb\r\n•\t.png →  x 17 = 51.6 mb\r\n•\t<b>Total = 106.4 mb</b>\r\n----\r\nBy Directory:\r\n•\tassets →  x 21 = 106.4 mb\r\n",
  "NeedleComponentsInScene": [
    "Needle.Engine.ExportInfo",
    "Needle.Engine.Codegen.ComponentGenerator",
    "Needle.Engine.Deployment.DeployToGlitch",
    "Needle.Engine.Components.GltfObject",
    "Needle.Engine.EditorSync.NeedleEditorSync",
    "Needle.Typescript.GeneratedComponents.MouseIncrementRotate"
  ],
  "TypeCacheIsDirty": false,
  "TypeScriptTypes": []
}
```

### Steps to reproduce 🔢

```bash
1. Have Needle Server running in a project
2. Try to export a bug report while the server is running
```

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marwie** [comment]
Hi, this happens when npm is currently reading/writing to a log file during creation of the bugreport. I'll close this as it's a fairly minor issue and only happens occasionally
