### ISSUE TITLE
Bloom Threshold not doing anything with Neutral Tonemapping on

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#141]
### Describe the bug 💬

When using Neutral Tonemapping and Bloom in a basic scene with the default Unity Skybox, Threshold doesn't seem to have any effect vs the editor, is there some extra configuration needed here for it to work?

This could partly be down to the emissive values I have chosen but I'm struggling to find anything that responds to the threshold in the Needle local server like the editor does

![bloomin](https://user-images.githubusercontent.com/10745594/229552008-1396893e-fb7e-4826-a12a-729758c0708a.gif)

### Operating System 👩‍💻

Windows

### What browsers are you seeing the problem on? 🏄‍♂️

Chrome

### Editor Version 🎲

2022.x

### Needle Exporter version

2.67.9-pre

### Project Info (Unity only) 📜

```json
{
  "ExportInfoGameObjectName": "Export Info",
  "ExportInfoGameObjectIsEnabled": true,
  "UnityProjectPath": "C:/Unity_Projects/EatonInteractive/Assets",
  "UnityVersion": "2022.2.12f1",
  "SceneName": "MainScene",
  "ProjectPath": "Needle/MainScene",
  "ProjectDirectoryExists": true,
  "ProjectIsInstalled": true,
  "NeedleEngineInstalled": true,
  "HasNodeInstalled": true,
  "NodeVersion": "v18.15.0",
  "NpmVersion": "9.6.2",
  "TypescriptVersion": "Version 5.0.2",
  "HasTokTxInstalled": true,
  "HasMinimumToktxVersionInstalled": true,
  "RenderPipeline": "URP-HighFidelity (UnityEngine.Rendering.Universal.UniversalRenderPipelineAsset)",
  "GzipEnabled": false,
  "NeedleEngineExporterVersion": "2.67.9-pre",
  "NeedleEngineVersion": "2.67.9-pre",
  "NeedleEngineExporterPath": "Packages/com.needle.engine-exporter/package.json",
  "NeedleEnginePath": "Packages/com.needle.engine/package.json",
  "FileStats": "By Type:\r\n•\t.glb →  x 2 = 1.4 mb\r\n•\t<b>Total = 1.4 mb</b>\r\n----\r\nBy Directory:\r\n•\tassets →  x 2 = 1.4 mb\r\n",
  "NeedleComponentsInScene": [
    "Needle.Engine.ExportInfo",
    "Needle.Engine.Codegen.ComponentGenerator",
    "Needle.Engine.Deployment.DeployToGlitch",
    "Needle.Engine.Components.GltfObject",
    "Needle.Engine.EditorSync.NeedleEditorSync",
    "Needle.Engine.Components.OrbitControls",
    "Needle.Typescript.GeneratedComponents.MouseIncrementRotate"
  ],
  "TypeCacheIsDirty": false,
  "TypeScriptTypes": []
}
```

### Steps to reproduce 🔢

```bash
1. Open the project, scenes> Main Scene
2. Hit play, see the Bloom threshold changes don't do anything vs the editor
```

### Reproduction ♻

https://github.com/needle-tools/needle-engine-support/files/11139462/Bugreport-MainScene-230403-034205_uw.zip

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ROBYER1** [comment]
A better screenshot, really struggling to figure out what's going on 
![image](https://user-images.githubusercontent.com/10745594/229553668-61a56409-fa5c-439b-bdb4-24a7835c8e52.png)

**Comment by hybridherbst** [comment]
What kind of emissive values do you have here? A threshold of 150 only starting to do something means that your materials are crazy bright. Is that intended? I don't think there will be any rendering fidelity match at such levels due to differences in tonemapping algorithms.

**Comment by ROBYER1** [comment]
I found some middle ground with Emissive Intensity on the material set to about 11, then on the Bloom set Threshold to 0.6, intensity to 60 but I had to use the clamp value set to 0.2 in the editor otherwise the emissive was blown way out like this 
![image](https://user-images.githubusercontent.com/10745594/229562283-66b0d4d9-ff72-4495-ac99-7ac7308d2f19.png)

Set lower:
![image](https://user-images.githubusercontent.com/10745594/229562387-73706a35-ca1a-4238-bb0f-0165e31030f9.png)

The material here, nothing crazy:
![image](https://user-images.githubusercontent.com/10745594/229562558-8e467eb0-6183-49d8-b1c8-e1a136e2ffef.png)

**Comment by ROBYER1** [comment]
With values closer to 1 of emissive I'm finding it matches up a lot closer, might close this for now as maybe it was my values but I'll keep an eye on it
