### ISSUE TITLE
Resetting a Particlesystem via script or deactivating a gameobject

### ISSUE THREAD

**Issue by Podden** [needle-tools/needle-engine-support#143]
### Describe the bug 💬

using stop() or play() on ParticleSystem does nothing for me. Also, disabling and enabling a gameobject with a particlesystem also does not reset it's particles like it does in Unity
My Code:
```typescript
import { Behaviour, GameObject, ParticleSystem } from "@needle-tools/engine";
export class NeedleParticleControl extends Behaviour {
    private ps: ParticleSystem | null = null;
    onEnable(): void {
            if (!this.ps) {
                this.ps = GameObject.getComponent(this.gameObject, ParticleSystem);
            }
            if (this.ps) {
                this.ps.play();
            }    
    }
    onDisable(): void {
            if (!this.ps) {
                this.ps = GameObject.getComponent(this.gameObject, ParticleSystem);
            }
            if (this.ps) {
                console.log("Stopping");
                this.ps.stop();
            }    
        }
}
```

### Operating System 👩‍💻

Windows

### What browsers are you seeing the problem on? 🏄‍♂️

Chrome

### Editor Version 🎲

2022.x

### Needle Exporter version

2.67.17

### Steps to reproduce 🔢

```bash
1. Add Particlesystem to Gameobject
2. Try to Activate/Deactivate Gameobject
3. Particles are not getting resettet
4. Use a Script and manually call particlesystem.Stop() and Play(), no reset either (there is not Clear() method in needle engine as far as I can say)
```

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marwie** [comment]
Regarding stop: currently the default behaviour is what unity has as a default I think with the StopBehaviour to just stop emitting and not clear

https://docs.unity3d.com/ScriptReference/ParticleSystem.Stop.html
https://docs.unity3d.com/ScriptReference/ParticleSystemStopBehavior.html

**Comment by marwie** [comment]
The next update adds ``reset()`` and arguments to ``stop()`` for stopping sub-emitters and also clearing the emitted particles

**Comment by marwie** [comment]
@Podden can you try if 3.x works for you?

**Comment by Podden** [comment]
Works in 3.6.1! I noticed that a particlesystem with activated prewarming does not get prewarmed a second time after calling stop. Maybe you should also add a function to prewarm it manually.
Otherwise, good work and thanks for fixing!
