### ISSUE TITLE
Shader Animation: alpha channel animation doesn't work

### ISSUE THREAD

**Issue by FrancisCortex** [needle-tools/needle-engine-support#144]
### Describe the bug 💬

I tried to animate the alpha channel of a custom shader. Animation doesn't work. Console Log in Browser said:"THREE.PropertyBinding: Trying to update property for track: .materials.Goal_Infill.color but it wasn't found."
![Kinder2023-04-18-43](https://user-images.githubusercontent.com/131183715/232828234-3b9a88e0-ef4e-4b4c-98d5-d6f92b05767c.png)
![Kinder2023-04-18-52](https://user-images.githubusercontent.com/131183715/232828209-ed2bc5fb-6940-44bd-adf2-e3077d24af7c.png)

### Operating System 👩‍💻

Windows

### What browsers are you seeing the problem on? 🏄‍♂️

Chrome

### Editor Version 🎲

2021.3

### Needle Exporter version

2.67.17

### Project Info (Unity only) 📜

```json
{
  "ExportInfoGameObjectName": "Export Info",
  "ExportInfoGameObjectIsEnabled": true,
  "UnityProjectPath": "D:/GIT/ukhalle-digivid/development/Digivid/Assets",
  "UnityVersion": "2021.3.15f1",
  "SceneName": "Digivid-Demo",
  "ProjectPath": "Needle/Digivid-Demo",
  "ProjectDirectoryExists": true,
  "ProjectIsInstalled": true,
  "NeedleEngineInstalled": true,
  "HasNodeInstalled": true,
  "NodeVersion": "v16.16.0",
  "NpmVersion": "8.11.0; npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.",
  "TypescriptVersion": "'\u0000t\u0000s\u0000c\u0000'\u0000 \u0000i\u0000s\u0000 \u0000n\u0000o\u0000t\u0000 \u0000r\u0000e\u0000c\u0000o\u0000g\u0000n\u0000i\u0000z\u0000e\u0000d\u0000 \u0000a\u0000s\u0000 \u0000a\u0000n\u0000 \u0000i\u0000n\u0000t\u0000e\u0000r\u0000n\u0000a\u0000l\u0000 \u0000o\u0000r\u0000 \u0000e\u0000x\u0000t\u0000e\u0000r\u0000n\u0000a\u0000l\u0000 \u0000c\u0000o\u0000m\u0000m\u0000a\u0000n\u0000d\u0000,\u0000; \u0000; \u0000o\u0000p\u0000e\u0000r\u0000a\u0000b\u0000l\u0000e\u0000 \u0000p\u0000r\u0000o\u0000g\u0000r\u0000a\u0000m\u0000 \u0000o\u0000r\u0000 \u0000b\u0000a\u0000t\u0000c\u0000h\u0000 \u0000f\u0000i\u0000l\u0000e\u0000.\u0000; \u0000; \u0000",
  "HasTokTxInstalled": true,
  "HasMinimumToktxVersionInstalled": false,
  "RenderPipeline": "URP-HighFidelity (UnityEngine.Rendering.Universal.UniversalRenderPipelineAsset)",
  "GzipEnabled": false,
  "NeedleEngineExporterVersion": "2.67.17",
  "NeedleEngineVersion": "2.67.17",
  "NeedleEngineExporterPath": "Packages/com.needle.engine-exporter/package.json",
  "NeedleEnginePath": "Packages/com.needle.engine/package.json",
  "FileStats": "By Type:\r\n•\t.glb →  x 6 = 89.1 mb\r\n•\t.mp3 →  x 65 = 10.0 mb\r\n•\t.json →  x 2 = 0.1 mb\r\n•\t.png →  x 2 = 0.2 mb\r\n•\t<b>Total = 99.5 mb</b>\r\n----\r\nBy Directory:\r\n•\tassets →  x 75 = 99.5 mb\r\n",
  "NeedleComponentsInScene": [
    "Needle.Engine.Components.GltfObject",
    "Needle.Typescript.GeneratedComponents.SceneSwitcher",
    "Needle.Engine.Components.WebXR",
    "Needle.Engine.Components.XRRig",
    "Needle.Engine.Components.OrbitControls",
    "Needle.Engine.ExportInfo",
    "Needle.Engine.Codegen.ComponentGenerator",
    "Needle.Engine.Deployment.DeployToFTP",
    "Needle.Engine.FontAdditionalCharacters"
  ],
  "TypeCacheIsDirty": false,
  "TypeScriptTypes": []
}
```

### Steps to reproduce 🔢

```bash
1.Create custom shader
2.references color
3.animate alpha channel
4. play and export needle
...
```

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marwie** [comment]
That works for me here:
https://user-images.githubusercontent.com/5083203/232987614-dfb3b6b7-8d92-4c42-98ef-ab3907aae9ef.mp4

**Comment by FrancisCortex** [comment]
Tried again - works fine now! Thanks
