### ISSUE TITLE
Unity Assertion Error on needle engine unity package import

### ISSUE THREAD

**Issue by Chudroy** [needle-tools/needle-engine-support#149]
### Describe the bug 💬

Operating System: Linux ...-ThinkPad-E14-Gen-3 5.19.0-42-generic #43~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC 2 x86_64 x86_64 x86_64 GNU/Linux

Error: Assertion failed
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /home/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:189)

Description: when i drag the needle engine unitypackage into unity, this error appears in the console and the import never starts. 

### Operating System 👩‍💻

Linux

### Editor Version 🎲

2021.3

### Needle Exporter version

n/a

### Steps to reproduce 🔢

```bash
1.download "Install Needle Engine Unity Integration.unitypackage" from https://engine.needle.tools/docs/getting-started/
2. drag it into unity 
3. error!
...
```

### Discord or Discussion link

https://discord.com/channels/717429793926283276/1024686103598477383/threads/1110952594848878652

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marwie** [comment]
Hi, I replied you in the discord already. I dont think this is related to Needle Engine but just an internal error in Unity.

Make sure to drop the unitypackage onto the ProjectWindow in Unity or double click to open it.

**Comment by Chudroy** [comment]
Thank you, I had to import it by going to assets > import package > custom package
