### ISSUE TITLE
Custom Shader Graph Shaders with Custom Function Node have Invalid Conditional Expression errors

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#16]
Using 2020.3.38f1 and Needle Engine Starter Project, I was trying to make a shadow catcher material using this https://brownbot.com/2021/03/09/realtime-ar-shadows-unity-shader-graph/

In the Shader, I get errors about 'Invalid Conditional Expression'

![image](https://user-images.githubusercontent.com/10745594/186903062-55c71a14-4a12-47c9-babd-cfed2a1fdee8.png)

Pretty much the same as this project and the file in it: https://github.com/Unity-Technologies/arfoundation-demos/blob/master/Assets/Shaders/Shadows/ShaderGraphs/TransparentShadowReceiver.shadergraph

Not sure if this is an error with the URP version or Needle? Is there an alternative for transparent AR plane shadow catching?

**Comment by ROBYER1** [comment]
Also I tried this shader from here https://forum.unity.com/threads/water-shader-graph-transparency-and-shadows-universal-render-pipeline-order.748142/#post-5518747 and it doesn't export correctly either, it exports as a solid colour

**Comment by hybridherbst** [comment]
@ROBYER1 the above screenshot looks like you're already getting errors in Unity. We're not influencing the workings of URP in any way (really only exporting the results), so you should first make sure that is working as intended.

Also a heads-up, as the docs mention custom shaders + lighting aren't supported right now – same goes for shadows. I believe you should be able to export a regular plane though and properly configure on three.js side to get the behaviour you want.

**Comment by ROBYER1** [comment]
I'll give that a shot thanks!
