### ISSUE TITLE
"Needle" banner in AR on iOS in commercial version

### ISSUE THREAD

**Issue by llllkatjallll** [needle-tools/needle-engine-support#161]
### Describe the bug 💬

On iOS in AR-View, when I do not fill out Custom Branding fields in "USDZ Exporter" component, there will be a "Made with Needle " label in the commercial needle version.

<img width="478" alt="20230704-132205-Acrobat" src="https://github.com/needle-tools/needle-engine-support/assets/38395689/39bb8b20-5589-4dd5-b8a9-66b0f25c913f">

<img width="617" alt="20230704-132449-Unity" src="https://github.com/needle-tools/needle-engine-support/assets/38395689/a8cf7f2e-4d39-46c4-bb5c-67f07ebbfa8f">

**Expectation:**
If the custom branding fields are empty, I would expect no other text in the banner. 

### Operating System 👩‍💻

Windows

### What browsers are you seeing the problem on? 🏄‍♂️

Safari

### Editor Version 🎲

2020.3

### Needle Exporter version

3.6.15

### Steps to reproduce 🔢

```bash
1. Add a USDZ Exporter component to ypur Unity project.
2. Leave "Custom Branding" empty.
3. Export project and test it on iOS in AR.
```

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marwie** [comment]
should be fixed in the next release > 3.7.5-alpha
