### ISSUE TITLE
SpatialTrigger Receiver fails to execute AudioSource.Play on Audiosource

### ISSUE THREAD

**Issue by pkirsten** [needle-tools/needle-engine-support#162]
### Describe the bug 💬

I use a Spatial Trigger Reciever, which should play a sound when a trigger object enters.
I connected an Audiosource in the On Enter Event and call AudioSource.Play.
I expected that the sound would play when I test it using the local server but the the renderer freezes and prompts the following error:

![image](https://github.com/needle-tools/needle-engine-support/assets/38910969/a4b3d798-d112-40f6-bcd3-095b53a35b30)

### Operating System 👩‍💻

Windows

### What browsers are you seeing the problem on? 🏄‍♂️

Chrome

### Editor Version 🎲

2021.3

### Needle Exporter version

3.6.13

### Project Info (Unity only) 📜

```json
{
  "ExportInfoGameObjectName": "Export",
  "ExportInfoGameObjectIsEnabled": true,
  "UnityProjectPath": "F:/Git/ukhalle-digivid/development/Digivid/Assets",
  "UnityVersion": "2021.3.15f1",
  "SceneName": "Audioplay",
  "ProjectPath": "Needle/Issues/Audioplay",
  "ProjectDirectoryExists": true,
  "ProjectIsInstalled": true,
  "NeedleEngineInstalled": true,
  "HasNodeInstalled": true,
  "NodeVersion": "v16.18.0",
  "NpmVersion": "8.19.2",
  "TypescriptVersion": "'\u0000t\u0000s\u0000c\u0000'\u0000 \u0000i\u0000s\u0000 \u0000n\u0000o\u0000t\u0000 \u0000r\u0000e\u0000c\u0000o\u0000g\u0000n\u0000i\u0000z\u0000e\u0000d\u0000 \u0000a\u0000s\u0000 \u0000a\u0000n\u0000 \u0000i\u0000n\u0000t\u0000e\u0000r\u0000n\u0000a\u0000l\u0000 \u0000o\u0000r\u0000 \u0000e\u0000x\u0000t\u0000e\u0000r\u0000n\u0000a\u0000l\u0000 \u0000c\u0000o\u0000m\u0000m\u0000a\u0000n\u0000d\u0000,\u0000; \u0000; \u0000o\u0000p\u0000e\u0000r\u0000a\u0000b\u0000l\u0000e\u0000 \u0000p\u0000r\u0000o\u0000g\u0000r\u0000a\u0000m\u0000 \u0000o\u0000r\u0000 \u0000b\u0000a\u0000t\u0000c\u0000h\u0000 \u0000f\u0000i\u0000l\u0000e\u0000.\u0000; \u0000; \u0000",
  "HasTokTxInstalled": true,
  "HasMinimumToktxVersionInstalled": true,
  "RenderPipeline": "URP-HighFidelity (UnityEngine.Rendering.Universal.UniversalRenderPipelineAsset)",
  "GzipEnabled": false,
  "NeedleEngineExporterVersion": "3.6.13",
  "NeedleEngineVersion": "3.6.15",
  "NeedleEngineExporterPath": "Packages/com.needle.engine-exporter/package.json",
  "NeedleEnginePath": "F:/Git/ukhalle-digivid/development/Digivid/Assets/../Needle/Issues/Audioplay/node_modules/@needle-tools/engine/package.json",
  "FileStats": "By Type:\r\n•\t.json →  x 1 = 0.0 mb\r\n•\t.png →  x 1 = 0.1 mb\r\n•\t.mp3 →  x 1 = 0.0 mb\r\n•\t.glb →  x 1 = 0.1 mb\r\n•\t<b>Total = 0.2 mb</b>\r\n----\r\nBy Directory:\r\n•\tassets →  x 4 = 0.2 mb\r\n",
  "NeedleComponentsInScene": [
    "Needle.Engine.ExportInfo",
    "Needle.Engine.Codegen.ComponentGenerator",
    "Needle.Engine.Deployment.DeployToGlitch",
    "Needle.Engine.Components.GltfObject",
    "Needle.Engine.Components.ObjectRaycaster",
    "Needle.Engine.Components.WebARSessionRoot",
    "Needle.Engine.Components.WebXR",
    "Needle.Engine.Components.OrbitControls",
    "Needle.Engine.Components.GridHelper",
    "Needle.Engine.Components.AxesHelper",
    "Needle.Engine.Components.SpatialTriggerReceiver",
    "Needle.Engine.Components.DragControls",
    "Needle.Engine.Components.SpatialTrigger"
  ],
  "TypeCacheIsDirty": false,
  "TypeScriptTypes": []
}
```

### Steps to reproduce 🔢

```bash
1.Create a Spatial Trigger and Spatial Trigger Reciever, setup to use the same mask
2.Create an Audiossource with an audioclip
3.Assign the Audiosource in the On Enter Event of Spatial Trigger Reciever
4.Move the Spatial Trigger into the Reciever
```

### Reproduction ♻

[Bugreport-Audioplay-230705-062137_uw.zip](https://github.com/needle-tools/needle-engine-support/files/11960094/Bugreport-Audioplay-230705-062137_uw.zip)

### Discord or Discussion link

https://prefrontalcortex.slack.com/archives/C03SCU2KF7B/p1688570465356399

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marwie** [comment]
should be fixed in 3.7.5-alpha
