### ISSUE TITLE
AR DOM Overlay not working

### ISSUE THREAD

**Issue by hosseinbannaei** [needle-tools/needle-engine-support#164]
### Describe the bug 💬

i want to use dom overlay to show some elements both in ar and desktop but whenever i put anything inside needle-engine tag with "ar" class (with or without desktop class) to use as container none of the elements inside it are visible in desktop or ar even the default close button of AR disappears
i thought maybe i'm doing something wrong, but even the HTML AR Overlay sample is not working when i create a project with it
and when i check any of my elements inside the container with inspector non of them show anything like width or height it's like their display is set to none but it's not
![image](https://github.com/needle-tools/needle-engine-support/assets/72253179/66dcabec-d3f7-467b-974c-29f4ede79bba)
![image](https://github.com/needle-tools/needle-engine-support/assets/72253179/d5eebbb1-2e88-4244-b4b4-5338a6b6a024)
![image](https://github.com/needle-tools/needle-engine-support/assets/72253179/47dd2d21-b26e-48ec-ae9e-250a1fd790f2)
without anything inside needle-engine tag :
![image](https://github.com/needle-tools/needle-engine-support/assets/72253179/fc28ef15-5588-4054-acea-a4b83a0e9a2b)

### Operating System 👩‍💻

Windows, Android (mobile)

### What browsers are you seeing the problem on? 🏄‍♂️

Chrome

### Editor Version 🎲

2022.x

### Needle Exporter version

3.7.6-pre

### Steps to reproduce 🔢

```bash
1.create a div inside the needle-engine tag and add "ar" class to it
2.put any normally visible element inside it
```

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marwie** [comment]
Hello, thanks for the report - we will take a look!

**Comment by marwie** [comment]
Hi the issue reproduced here and we are working on a fix.

**Comment by marwie** [comment]
Hello, can you try with 3.9.x ?

**Comment by hosseinbannaei** [comment]
Hello, sorry for the late reply
Yes,I tested it and it works, thank you very much
