### ISSUE TITLE
Editor Sync: X-Axis flipped when editing via inspector

### ISSUE THREAD

**Issue by krisrok** [needle-tools/needle-engine-support#172]
### Describe the bug 💬

The X-Axis is flipped when editing a transform's position via inspector.

### Operating System 👩‍💻

Windows

### What browsers are you seeing the problem on? 🏄‍♂️

Firefox, Chrome

### Editor Version 🎲

2021.3

### Needle Exporter version

~3.6.9~ 3.11.1-pre

### Project Info (Unity only) 📜

```json
{
  "ExportInfoGameObjectName": "Export",
  "ExportInfoGameObjectIsEnabled": true,
  "UnityProjectPath": "needle-2021.3/Assets",
  "UnityVersion": "2021.3.27f1",
  "SceneName": "Minimal",
  "ProjectPath": "Needle/Minimal",
  "ProjectDirectoryExists": true,
  "ProjectIsInstalled": true,
  "NeedleEngineInstalled": true,
  "HasNodeInstalled": true,
  "NodeVersion": "v18.16.0",
  "NpmVersion": "9.5.1",
  "TypescriptVersion": "'\u0000t\u0000s\u0000c\u0000'\u0000 \u0000i\u0000s\u0000 \u0000n\u0000o\u0000t\u0000 \u0000r\u0000e\u0000c\u0000o\u0000g\u0000n\u0000i\u0000z\u0000e\u0000d\u0000 \u0000a\u0000s\u0000 \u0000a\u0000n\u0000 \u0000i\u0000n\u0000t\u0000e\u0000r\u0000n\u0000a\u0000l\u0000 \u0000o\u0000r\u0000 \u0000e\u0000x\u0000t\u0000e\u0000r\u0000n\u0000a\u0000l\u0000 \u0000c\u0000o\u0000m\u0000m\u0000a\u0000n\u0000d\u0000,\u0000; \u0000; \u0000o\u0000p\u0000e\u0000r\u0000a\u0000b\u0000l\u0000e\u0000 \u0000p\u0000r\u0000o\u0000g\u0000r\u0000a\u0000m\u0000 \u0000o\u0000r\u0000 \u0000b\u0000a\u0000t\u0000c\u0000h\u0000 \u0000f\u0000i\u0000l\u0000e\u0000.\u0000; \u0000; \u0000",
  "HasTokTxInstalled": true,
  "HasMinimumToktxVersionInstalled": true,
  "RenderPipeline": "Built-in",
  "GzipEnabled": false,
  "NeedleEngineExporterVersion": "3.11.1-pre",
  "NeedleEngineVersion": "3.11.1-beta",
  "NeedleEngineExporterPath": "Packages/com.needle.engine-exporter/package.json",
  "NeedleEnginePath": "needle-2021.3/Assets/../Needle/Minimal/node_modules/@needle-tools/engine/package.json",
  "FileStats": "By Type:\r\n•\t.glb →  x 1 = 0.1 mb\r\n•\t<b>Total = 0.1 mb</b>\r\n----\r\nBy Directory:\r\n•\tassets →  x 1 = 0.1 mb\r\n",
  "NeedleComponentsInScene": [
    "Needle.Engine.ExportInfo",
    "Needle.Engine.Codegen.ComponentGenerator",
    "Needle.Engine.Deployment.DeployToGlitch",
    "Needle.Engine.EditorSync.NeedleEditorSync",
    "Needle.Engine.Components.GltfObject",
    "Needle.Engine.Components.ObjectRaycaster",
    "Needle.Engine.Components.WebARSessionRoot",
    "Needle.Engine.Components.WebXR",
    "Needle.Engine.Components.OrbitControls",
    "Needle.Engine.Components.GridHelper",
    "Needle.Engine.Components.AxesHelper",
    "Needle.Typescript.GeneratedComponents.MyOtherScript"
  ],
  "TypeCacheIsDirty": false,
  "TypeScriptTypes": []
}
```

### Steps to reproduce 🔢

1. Set up any project with Editor Sync
2. Make sure it works correctly (e.g. by using scene camera sync)
3. Move an object by playing with the X-Value in the inspector
4. ~See the object jump around between positive and negative x-value position~ The object's X-Axis is flipped. If you edit via scene view, it moves to the right side again.

### Discord or Discussion link

https://discord.com/channels/717429793926283276/1118464770849374229

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by krisrok** [comment]
Please note I created this issue based on an older engine version (I stumbled upon this a while ago, see discord link).

I've just updated the engine to 3.11.1-pre and confirmed the bug's still there although without the jumping around. Will update the first post.

**Comment by marwie** [comment]
Hi, thanks again for the report and sorry for the late reply. This will be fixed in the next version
