### ISSUE TITLE
CSS changes in .webxr-buttons  in the style.css are being ignored

### ISSUE THREAD

**Issue by llllkatjallll** [needle-tools/needle-engine-support#173]
### Describe the bug 💬

I want to change the position of the webxr-buttons in the style.css document (I was able to do this in previous projects).

But when I change some css-values now (for example bottom-value) , test it on mobile and debug it with chrome - the default values of the webxr-buttons css are shown.

### Operating System 👩‍💻

Windows

### What browsers are you seeing the problem on? 🏄‍♂️

Chrome

### Editor Version 🎲

2021.3

### Needle Exporter version

3.10.5-pre

### Project Info (Unity only) 📜

```json
## <TITLE>
## Describe the bug
needle-engine .webxr-buttons CSS changes in the style.css are being ignored

## Steps to reproduce
1) Change values (for example bottom-value) for .webxr-buttons class.
2) Test the project on mobile
3) Changes made in css are not visible

## How can we contact you if we have further questions?
- krempel
- discord username: krempel
- link to discord post or github issue
```

### Steps to reproduce 🔢

```bash
1) Change values (for example bottom-value) for .webxr-buttons class.
2) Test the project on mobile
3) Changes made in css are not visible
```

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hybridherbst** [comment]
That's expected as the buttons have moved into the shadowRoot of the needle-engine element, where they can't be styled. We'll have to add a <slot> for it so you can override them more easily; as a workaround, you can use the custom XR buttons sample as basis for rolling your own buttons.
