### ISSUE TITLE
Opening .ts files is somewhat broken

### ISSUE THREAD

**Issue by krisrok** [needle-tools/needle-engine-support#175]
### Describe the bug 💬

Opening a .ts file via inspector's "Open foo.ts" leads to some info and warning log entries on Windows:
```
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

## [ ] Use VSCode 
I had unchecked "[ ] Use VSCode" because I wanted to try and use VS instead of VSCode so I investigated a little bit. The quoting for ProcessStartInfo is incorrect:
In `WorkspaceUtils` L64 you should quote the executable path too (_and_ for VS omit the `/Edit` to correctly open a solution in folder view):
```
await ProcessHelper.RunCommand("\"" + inst + "\"" + " \"" + directory + "\"", null);
```
and when using `cmd /u /c` in `ProcessHelper` L339 you should quote the whole command again:
```
si.Arguments = $"/u /c \"{command}\"";
```
That then leads to VS starting up with the correct folder, yay. Sadly, the .ts file itself might open on whatever open VS instance it pleases and I stopped here.

## [x] Use VSCode
Now I checked "[x] Use VSCode" again and tried to open a .ts file. But with my fixes in place it now opens VS in folder view _and_ the file in VSCode. That can't be right :)

Without my fixes it also tries to start VSCode _and_ VS:
```
'code' is not recognized as an internal or external command,
operable program or batch file.
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

### Operating System 👩‍💻

Windows

### Editor Version 🎲

2021.3

### Needle Exporter version

3.11.4-pre

### Steps to reproduce 🔢

```bash
1. Open .ts file via inspector
```

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marwie** [comment]
Hi @krisrok thanks for the report and detailed information
I'll try to reproduce that here

**Comment by marwie** [comment]
Hi @krisrok it should be fixed in the next update. Again thanks for the report

**Comment by krisrok** [comment]
Thanks!

Did you also have the chance to look at opening individual .ts files with the correct VS instance (instead of the last active one)? This seems to be a bit trickier as VS does not know where the file belongs (not part of any "real" solution).

**Comment by krisrok** [comment]
I'd say it's a partial fix. This should maybe be split to several issues. 

Please understand the thumbs up/down as "desired"/"undesired" :)

## [ ] Use VScode
- "Open workspace"
    - If no VS instance is already open:
        - It correctly opens in folder view 👍 
        - The "background tasks" in Unity displays an entry as long as this VS instance is alive 👎 
    - If any other VS instance is already open
       - Its main window pops into foreground, nothing else happens 👎 
- "Open foo.ts"
    - If "Open workspace" went through (see above)
        - It correctly opens the file in the (only) VS instance
    - If no VS instance is already open:
       - It opens the workspace in folder view 👍 
       - Additionally, it opens foo.ts in a separate instance 👎
   - If any other VS instance is already open
      - It does not open the workspace but opens foo.ts in the unrelated VS instance instead 👎 

## [x] Use VSCode
- "Open workspace"
    - Works, as before👍 
    - But still emits `'code' is not recognized as an internal or external command, operable program or batch file.` in two separate log entries 👎 
- "Open foo.ts"
    - If no VS instance is already open:
       - It opens the workspace VSCode 👍
       - Additionally, it opens the workspace in folder view in a new VS instance 👎
   - If any other VS instance is already open
      - It opens foo.ts in VSCode 👍
      - Before VSCode gains focus, the VS instance is called to foreground for a sec 👎
