### ISSUE TITLE
CodeGen stops working, incorrectly warns about Node.js not installed

### ISSUE THREAD

**Issue by krisrok** [needle-tools/needle-engine-support#177]
### Describe the bug 💬

I managed to solve it by myself but the warning really was not of much help:

What I found out:
- The problem was another CodeGen process was hanging in the background (maybe due to crashed Unity process) and kept a handle on the log file.
- CodeGen has a somewhat error-prone check that relies on Node.js writing its version to the log file.

What happened:
- Log file was locked -> No version was written -> Needle Exporter warns about Node.js not present -> User confused

### Operating System 👩‍💻

Windows

### Editor Version 🎲

2021.3

### Needle Exporter version

3.12.2-pre

### Steps to reproduce 🔢

```bash
1. See description above :)
```

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marwie** [comment]
Thanks for the report!
