### ISSUE TITLE
Editor Sync: Messing with UnityEvents

### ISSUE THREAD

**Issue by krisrok** [needle-tools/needle-engine-support#180]
### Describe the bug 💬

Deserialization breaks when the event list is changed via inspector while ES is active.
As the ES changes persist, the session has to be killed by restarting vite.

### Operating System 👩‍💻

Windows

### What browsers are you seeing the problem on? 🏄‍♂️

Chrome

### Editor Version 🎲

2021.3

### Needle Exporter version

3.14.0-pre

### Steps to reproduce 🔢

```bash
1) Export and start the scene with ES
2) The grid should blink on and off (triggered by _boolEvent), the Cube should move (triggered by _nonGenericEvent).
3) Modify one of the events via inspector (e.g. by clicking on the +)
4) Watch the triggers not working anymore (grid should stop blinking or Cube moving, depending on which event was modified)
5) Reload page => Triggers not working anymore
6) Restart vite and reload page => Triggers working until events get modified again
```

### Reproduction ♻

Uploaded as Bugreport-Minimal 1-230913-115251_uw.zip

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marwie** [comment]
Hi, thanks for the report.

The next version will ignore UnityEvent modifications for now and add an `EditorModificationHandler.HandleChange` event which can be used to ignore certain modifications (the arguments have the target object, propertyname and value as well as a bool for ` preventDefault`. Setting this to true will ignore the change). 

This event also allows to modify the target and object data if necessary
