### ISSUE TITLE
Rapier runtime errors when instantiating prefabs with colliders attached

### ISSUE THREAD

**Issue by snorulf** [needle-tools/needle-engine-support#185]
### Describe the bug 💬

Getting runtime errors lately using NE 3.25.3, not sure at which version this actually broke but I started noticing it today when running a scene which loads prefabs/glbs with collider components.

Scene loads several (15-20) npc  different prefabs with animator animations using:
```
async awake() {
  await this.prefabObject?.instantiate(this.gameObject);
}
```

I sort of verified that it was the NE version causing this by reverting to a commit I did 14 days ago when I know things were working fine and doing a complete reinstall + export which gave me the same issue.

Console output:
```
debug_overlay.ts:23 Error creating collider "HansA"
Error: Error: recursive use of an object detected which would lead to unsafe aliasing in rust
    at I3.wbg.__wbindgen_throw (rapier_wasm3d.js:4504:15)
    at 00527bbe:0x139b1b
    at 00527bbe:0x139b37
    at 00527bbe:0xe2e4f
    at H.createCollider (rapier_wasm3d.js:932:18)
    at MI.createCollider (collider_set.ts:79:31)
    at sI.createCollider (world.ts:342:31)
    at _RapierPhysics.createCollider (engine_physics_rapier.ts:760:36)
    at _RapierPhysics.addBoxCollider (engine_physics_rapier.ts:534:14)
    at BoxCollider.onEnable (Collider.ts:101:38)
```

Could it have been caused by the recent performance improvement in 3.25.3? I'm not really a web developer so I don't know how to revert to previous NE runtime versions and verify. 

### Operating System 👩‍💻

Windows, Android (mobile)

### What browsers are you seeing the problem on? 🏄‍♂️

Chrome

### Editor Version 🎲

2022.x

### Needle Exporter version

3.25.3 and 3.21.2

### Steps to reproduce 🔢

```bash
1. instantiate prefab object with collider attached using 
async awake() {
  await this.prefabObject?.instantiate(this.gameObject);
}
2. Sometimes I had to load several objects this way to repro the issue.

Hope this helps.
```

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marwie** [comment]
Hi, thanks for the report. Can you try if it still happens with version 3.25.4 ?

**Comment by snorulf** [comment]
Yup, 3.25.4 seems fix it. Thanks
