### ISSUE TITLE
3.40.0-exp Unity 2021.3.6f1

### ISSUE THREAD

**Issue by pundirmr** [needle-tools/needle-engine-support#193]
### Describe the bug 💬

I am on macOS. Unity version 2021.3.6f1, Silicon unity version
After importing the .unitypackage, getting errors in console. 

```
Library/PackageCache/com.needle.engine-exporter@3.40.0-exp/Common/Runtime/NeedleEngineModules.cs(23,21): error CS0117: 'Object' does not contain a definition for 'FindAnyObjectByType'
Library/PackageCache/com.needle.engine-exporter@3.40.0-exp/Common/Runtime/NeedleEngineModules.cs(40,15): error CS0117: 'Object' does not contain a definition for 'FindAnyObjectByType'
Library/PackageCache/com.needle.engine-exporter@3.40.0-exp/Common/Runtime/NeedleEngineModules.cs(41,15): error CS0117: 'Object' does not contain a definition for 'FindAnyObjectByType'
Library/PackageCache/com.needle.engine-exporter@3.40.0-exp/Core/Editor/Internals/BuildTarget/TextureImportSettings.cs(61,43): error CS1061: 'TextureImportPlatformSettingsData' does not contain a definition for 'maxTextureSizeProperty' and no accessible extension method 'maxTextureSizeProperty' accepting a first argument of type 'TextureImportPlatformSettingsData' could be found (are you missing a using directive or an assembly reference?)
Library/PackageCache/com.needle.engine-exporter@3.40.0-exp/Core/Editor/Internals/BuildTarget/TextureImportSettings.cs(63,44): error CS1061: 'TextureImportPlatformSettingsData' does not contain a definition for 'maxTextureSizeProperty' and no accessible extension method 'maxTextureSizeProperty' accepting a first argument of type 'TextureImportPlatformSettingsData' could be found (are you missing a using directive or an assembly reference?)
```

<img width="1211" alt="image" src="https://github.com/needle-tools/needle-engine-support/assets/50841804/73d5e573-182f-4778-9203-9235d3a76e34">

### Operating System 👩‍💻

macOS

### Editor Version 🎲

2021.3

### Needle Exporter version

3.40.0-exp

### Steps to reproduce 🔢

```bash
1. Import unity package 3.40.0-exp in Unity 2021.3.6f1
2.
3.
...
```

### Validations 🩹

- [X] Follow our [Code of Conduct](https://github.com/needle-tools/needle-engine-support/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://docs.needle.tools).
- [X] Check that there isn't [already an issue](https://github.com/needle-tools/needle-engine-support/issues) that reports the same bug to avoid creating a duplicate.
- [X] Make sure this is a Needle-Engine-specific issue. For example if it's a Unity related bug, it should be reported to [Unity](https://unity3d.com/unity/qa/bug-reporting) instead.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/needle-tools/needle-engine-support/discussions) or join our [Discord Chat Server](https://discord.needle.tools).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kipash** [comment]
Please update your Unity 2021.3 LTS to the latest patch and try again (2021.3.39f1)

**Comment by marwie** [comment]
@pundirmr please reopen the issue if updating didnt fix it for you
