### ISSUE TITLE
Exported UI Buttons seem to just be white squares now

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#29]
Using Exporter 2.12.1-pre, Unity 2020.3.38f1

Exported UI Buttons seem to just be white squares now

![image](https://user-images.githubusercontent.com/10745594/187395215-57d1f644-2b68-4e41-b07c-eeeea0c63d20.png)

**Comment by marwie** [comment]
Please put them inside a gltf file now

**Comment by ROBYER1** [comment]
That was it, thanks
