### ISSUE TITLE
Animated UI anchored position incorrect + jittering

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#30]
Using Exporter 2.13.0-pre in Unity 2020.3.38f1

Exported UI with a button that is animated (another button is a child of it, rotated 180 degrees so the button is 2 sided on the web). Added keyframes for scale, move and rotate and the animation is jittering + the button seems to be floating forward from its position when I only animated it flying up not forward.

Hope the gif helps and I can send a repro if needed

![wbbblbutton](https://user-images.githubusercontent.com/10745594/187694169-d3bdc072-49ef-43bc-98f0-554159e5e723.gif)

**Comment by marwie** [comment]
please try 2.18.3-pre if it is fixed

**Comment by ROBYER1** [comment]
> please try 2.18.3-pre if it is fixed
> 
> animating UI elements with animationclips is still not fully supported tho

Looks better, shall I wait to close this when animations are better supported? Otherwise please close

**Comment by marwie** [comment]
Lets close this for now and re-open if it happens again (i think it should not break like in the video anymore)
