### ISSUE TITLE
Creating a script in src/scripts doesn't generate a C# script in Unity with Engine 2.10.1-pre

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#32]
I have been following the example workflow recently and the C# components don't get auto-generated, is there a reason why or is there also a way to force it to generate the C# scripts?

Using Unity 2020.3.38f1 and Needle Engine 2.10.1-pre + Exporter 2.13.0-pre

![image](https://user-images.githubusercontent.com/10745594/187888459-112edfec-dae2-4a45-bd1e-113f2ee7b2f1.png)

**Comment by marwie** [comment]
Can you try enabling / disabling the ComponentCompiler component?

**Comment by ROBYER1** [comment]
> Can you try disabling + enabling the ComponentCompiler component? And then save your script again?

That worked! I had to save the script a few times for it to work for one of them I made, at least this issue is known

**Comment by marwie** [comment]
Would be great if you could keep an eye on it from version 2.14.0 (just released) if it happens again

**Comment by ROBYER1** [comment]
Working good in 2.14.0 so closing
