### ISSUE TITLE
Identical named gameobjects override each other on export

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#33]
Use template scene, add 2x Worldspace Canvas, add gltf Object component to them and make sure they are both called Canvas.

Add a button or image to each so you can see which is which - only one of them will show when you export is they are named identical.

If you change their names to Canvas1 and Canvas2, they both show

**Comment by hybridherbst** [comment]
Good catch, objects with GltfObject on them need to have unique names right now. Inside them they can have duplicate names though.

**Comment by ROBYER1** [comment]
> Good catch, objects with GltfObject on them need to have unique names right now. Inside them they can have duplicate names though.

Can be something I noticed a lot when making new objects in Unity as they aren't always renamed, or prefabs being used etc. Is there any way to warn the user about this on export? Could be just a documentation mention but it was confusing me when I was adding prefabs to scenes quickly

**Comment by hybridherbst** [comment]
Question is why you want so many separate GLBs if you're loading them at the same time anyways - usually we just have one or maybe a few such "roots" in a project unless there's very specific reasons for having more.

**Comment by ROBYER1** [comment]
I'll probably mark this as a non-issue!
