### ISSUE TITLE
Setup error on work computer: Win32Exception: ApplicationName='cmd.exe', CommandLine='/c npm', CurrentDirectory='', Native error= The system cannot find the file specified.

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#34]
We get the following errors on a fresh clone and open of the Needle Engine Starter repo (cloned with LFS on) using Unity 2020.3.38f1

We have installed Node.js and restarted, versions:
node v16.17.0
npm 8.15.0

Needle tools tutorial popup window says 'Installing nodejs' with advice to restart computer 

`
Win32Exception: ApplicationName='cmd.exe', CommandLine='/c npm', CurrentDirectory='', Native error= The system cannot find the file specified.
—
System.ComponentModel.Win32Exception: ApplicationName='cmd.exe', CommandLine='/c npm', CurrentDirectory='', Native error= The system cannot find the file specified.
`

`
Win32Exception: ApplicationName='cmd.exe', CommandLine='/c npm set registry https://registry.npmjs.org && npm install --force --progress=false 2>&1 > "D:/Unity/Needle/starter/Needle Engine Starter 2020_3/Assets/../Temp/NeedleTinyCmdProcess.log"', CurrentDirectory='D:\Unity\Needle\starter\Needle Engine Starter 2020_3\Library\PackageCache\com.needle.engine@2.10.2-pre\package~', Native error= The system cannot find the file specified.
—
System.ComponentModel.Win32Exception: ApplicationName='cmd.exe', CommandLine='/c npm set registry https://registry.npmjs.org && npm install --force --progress=false 2>&1 > "Assets/../Temp/NeedleTinyCmdProcess.log"', CurrentDirectory='Library/PackageCache/com.needle.engine@2.10.2-pre/package~', Native error= The system cannot find the file specified.
`

**Comment by hybridherbst** [comment]
Have you restarted the machine, and made sure that node + npm are in the PATH (environment variables)? If that's unchecked on installation then we're not able to find the right path at the moment.

**Comment by ROBYER1** [comment]
Confirmed that Nodejs is in the path in the correct place, we are stumped

**Comment by hybridherbst** [comment]
When you open a regular terminal on that machine and type `cmd.exe` and press enter, what happens?

Should look like this:
![image](https://user-images.githubusercontent.com/2693840/187940678-627334b4-d53e-49f5-b68e-b9f3186ecc72.png)

Sounds like cmd.exe can't be found?!

**Comment by ROBYER1** [comment]
Confirmed that is the issue, looking into why cmd.exe cannot work

**Comment by ROBYER1** [comment]
Fixed after adding Windows\System32 then rebooting the pc once again
