### ISSUE TITLE
'CompileVariant' and no accessible extension method 'CompileVariant' accepting a first argument of type 'ShaderData.Pass' 

### ISSUE THREAD

**Issue by Hisaack** [needle-tools/needle-engine-support#35]
Hi there,

I am using Unity 2020.3.3f1, and when I installed the package via Registry, this is the error I keep on getting.. Any attempt to resolve it?

Thanks.

Library\PackageCache\com.needle.engine-exporter@2.14.2-pre\Shaders\Editor\ShaderExporter.cs(110,30): error CS1061: 'ShaderData.Pass' does not contain a definition for 'CompileVariant' and no accessible extension method 'CompileVariant' accepting a first argument of type 'ShaderData.Pass' could be found (are you missing a using directive or an assembly reference?)

**Comment by marwie** [comment]
Hello, could you upgrade to a newer version of Unity (e.g. 2020.3.33f1 or later) ?

**Comment by hybridherbst** [comment]
Closing as this was on an unsupported Unity version.
