### ISSUE TITLE
Clicking on World Space UI Canvas disables ability to rotate camera

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#4]
Not sure if this is unique to the example scene you get with the cacti when you make a new scene using the getting started popup:

1. Make a new scene with the cactus example
2. Make a world space UI canvas with 2 regular buttons in it
3. Place the canvas and scale it so it fits in the middle of the scene to easily press
4. Export and play using the Export gameobject
5. Click the buttons in the canvas and notice the left click camera rotation no longer works, nor does the scroll or right click move

**Comment by marwie** [comment]
Thanks for the great repro steps! Just reproduced it and will now try to figure out whats going on

**Comment by marwie** [comment]
Should be fixed in the next version! Thanks for reporting
