### ISSUE TITLE
Scale of child objects affects other objects in GLTF file

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#40]

**Comment by hybridherbst** [comment]
@ROBYER1 mind clarifying what this was about? :)

**Comment by ROBYER1** [comment]
It was actually caused by . getWorldPosition setting the position Vector on a transform, I was thinking some cubes in my scene had moved when I rescaled a plane but it was actually code grabbing their world position moving them.

Please delete if possible (I couldn't see how to delete)
