### ISSUE TITLE
Animations don't allow enable/disable of components

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#41]
I was trying to use a script that would run something in onEnable and onDisable and was finding those events don't fire when the gameobject itself was enabled or disabled. So I tried animating the component itself enable/disabling on the animation track instead of the gameobject it is on. I get this error:

`three.module.js:44609 THREE.PropertyBinding: Trying to update property for track: .nodes.CamResetter.userData.components.0.m_Enabled but it wasn't found. `

Sample code, using my OrbitControlsEpm script but these onEnable/onDisable don't fire when the Gameobject it is is set active/inactive in an animation:
```
import { Behaviour, GameObject } from "@needle-tools/engine/engine-components/Component";
import { serializeable } from "@needle-tools/engine";
import * as THREE from "three";
import { Object3D } from "three";
import { OrbitControlsEpm } from "./OrbitControlsEpm";

export class ResetCameraPos extends Behaviour
{
    @serializeable(OrbitControlsEpm)
    public orbitCam?: OrbitControlsEpm;

    @serializeable(GameObject)
    public target?: GameObject;

    onEnable()
    {
        this.orbitCam?.setTarget(this.target);
    }

    onDisable()
    {
        console.log("disabling");
        this.orbitCam?.enableDisableControls();
    }
}
```

**Comment by ROBYER1** [comment]
Ah, great! If onEnable/onDisable firing when the animation sets the gameobject itself active/inactive too that would be good as sometimes I would rely on onEnable/onDisable during animations

**Comment by marwie** [comment]
@ROBYER1 you can as a workaround declare this property on our objects too. You are in javascript land after all.

Just add the following code somewhere in your scripts should do the trick:
```ts
Behaviour.prototype["m_Enabled"] = function(value) {
 this.enabled = value;
};

**Comment by ROBYER1** [comment]
> @ROBYER1 you can (as a workaround) declare this property on Needle Engine objects too. You are in javascript land after all 😅
> 
> Just add the following code somewhere in your scripts, that should do the trick:
> 
> ```ts
> Behaviour.prototype["m_Enabled"] = function(value) {
>  this.enabled = value;
> };
> ```

I'll be sure to try this!

**Comment by marwie** [comment]
I can also add it to our component in the next update until it's properly fixed in the exporter. But just so you know as it might not the last time 😅

**Comment by marwie** [comment]
Ah sorry I have to correct my comment above. In this case you have to declare it as a property. But it works the same way

Like this:

```ts
Object.defineProperty(Behaviour.prototype, "m_Enabled", {
    set: function m_Enabled(val: boolean) {
        this.enabled = val;
    },
    get: function m_Enabled(): boolean {
        return this.enabled;
    }
});
```

**Comment by marwie** [comment]
This should work in 2.20.0 pre now by default
