### ISSUE TITLE
UI Anchoring and Positioning is off

### ISSUE THREAD

**Issue by sabi-wasabi** [needle-tools/needle-engine-support#42]
When anchoring the text or image component, the anchoring will be mirrored when exporting (left and right is switched). 

Set it up in Unity like this: 
<img width="780" alt="unityAnchoring" src="https://user-images.githubusercontent.com/62065990/188658229-5932bdbc-75e9-48e6-b771-17ed2d099aab.PNG">

And got this result: 
<img width="917" alt="webResultAnchoring" src="https://user-images.githubusercontent.com/62065990/188658342-da5302f9-bfbe-413f-9e8f-bdd0c43114c0.PNG">

Version: 2.16.0-pre (Exporter) and 2.12.o-pre (Engine)

**Comment by ROBYER1** [comment]
Could be related to https://github.com/needle-tools/needle-engine-support/issues/10 Check your canvas rotation?

**Comment by sabi-wasabi** [comment]
The canvas wasn't rotated. However i noticed that when moving the parent (gltf object) of a canvas, the canvas will be moved way more (guessing the translation is somehow applied to the canvas as well, essentially moving it twice?)

Unity Setup with the right one being at the origin:
<img width="1323" alt="Screenshot 2022-09-07 072911" src="https://user-images.githubusercontent.com/62065990/188796270-1e17ae18-5c07-409a-8ce3-424c51511fd0.png">

In the browser:
<img width="1185" alt="Screenshot 2022-09-07 072952" src="https://user-images.githubusercontent.com/62065990/188796316-526a0ec5-3ee2-4038-b74b-02e6c4688799.png">

**Comment by ROBYER1** [comment]
Noticing this in my project too! See the UI Button is on the wrong side completely 
![image](https://user-images.githubusercontent.com/10745594/188907906-c4942471-da8c-4a4c-a7ea-93776e81dcfa.png)

**Comment by marwie** [comment]
Will be fixed in the next update :)

**Comment by marwie** [comment]
please try 2.18.3-pre if it is fixed

**Comment by ROBYER1** [comment]
> please try 2.18.3-pre if it is fixed

![image](https://user-images.githubusercontent.com/10745594/190111087-226bac7a-eb9c-406d-ab38-e95f404c7299.png)

@marwie It is still off here, canvas is at 0.42 y worldspace and 0 the rest, button is always off on position still from editor to the export - I can send you a repro zip if need be.

**Comment by marwie** [comment]
Hey @ROBYER1 yes please send a repo. Just tried in the UI button sample here which looks fine for me https://github.com/needle-tools/needle-engine-samples
 
That is on 2.22.0-pre
