### ISSUE TITLE
Create new component does not work for me

### ISSUE THREAD

**Issue by metiscoda** [needle-tools/needle-engine-support#43]
Following the instructions here: https://github.com/needle-tools/needle-engine-support/blob/main/documentation/scripting.md#creating-a-new-component

I created a new file at ~/Documents/Projects/Unity/needleToolsTest/Projects/NeedleTest1/src/scripts called Rotate.ts and copied the contents of the example in there.  But there was no Unity component created.  Is there something that needs to be done for the detection to occur?

**Comment by marwie** [comment]
Can you try to toggle the component generatoe component in unity and then save your script again? Its a known issue and should be fixed soon.

Sorry for the inconvenience

**Comment by metiscoda** [comment]
Nice! That seems to have worked, thanks!

**Comment by marwie** [comment]
Great!
