### ISSUE TITLE
UI Shows up as white squares - Exporter 2.17.0-pre

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#45]
Using Exporter 2.17.0-pre try to export a worldspace canvas with buttons, they show up as white squares

![image](https://user-images.githubusercontent.com/10745594/188836799-fad8db6c-a936-4815-8522-c4f1aa9b1eb5.png)

Unticking Generate Report in Needle Settings fixes this but it's not a proper fix imo

**Comment by marwie** [comment]
Reproduces here - working on a fix right now

**Comment by ROBYER1** [comment]
Fixed in 2.17.1-pre
