### ISSUE TITLE
.gitignore is sometimes missing from generated projects

### ISSUE THREAD

**Issue by hybridherbst** [needle-tools/needle-engine-support#48]
This can be very confusing as suddenly version control shows ~40.000 changes (everything in node_modules) instead of the ~35 changes generating a project actually should show.

Still not sure in which conditions this happens.

--------

For people stumbling upon this issue, here's the .gitignore that should be generated inside each project's folder:
```
node_modules/
assets/
src/generated/
dist/
stats.html
include/draco/
include/ktx2/
include/three/
include/console/
include/three-mesh-ui-assets/
cache~
```

**Comment by marwie** [comment]
Should be fixed in next update
