### ISSUE TITLE
Fix Create Git Ignore Fix failed: Could not find any gitignore to create - Exporter 2.18.0-pre

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#51]
Using Exporter 2.18.0-pre in the starter project cloned from here (and the repro projects I sent), the warning 

The warning here has incorrect capitalisation of 'Projects\newProject', it should be 'projects\newProject'
![image](https://user-images.githubusercontent.com/10745594/189078557-e56a7a2f-bd5b-4c8b-860b-27cb69734a16.png)

I get this in console always: Fix Create Git Ignore Fix failed: Could not find any gitignore to create

Could be if there is no gitignore, make a blank one automatically and log a warning (not error) about it?

**Comment by ROBYER1** [comment]
This blocks install or clean install on the Export Info component also

**Comment by marwie** [comment]
Oh sorry - fixed that in 2.18.1-pre (just published)
