### ISSUE TITLE
Why I can't find npm path?

### ISSUE THREAD

**Issue by Kelier** [needle-tools/needle-engine-support#54]
already installed node and restart my computer

**Comment by Kelier** [comment]
<img width="904" alt="image" src="https://user-images.githubusercontent.com/16694478/190140012-e602dc53-53fd-4049-bdf2-65d0e1049474.png">

**Comment by marwie** [comment]
How did you install nodejs? 
Please run ``which npm`` and add the search paths to the settings in the **Additional npm Search Paths`` field

![image](https://user-images.githubusercontent.com/5083203/190144236-4e6e6ddb-18f3-4c7c-9ec0-52f0f6dc7157.png)

**Comment by marwie** [comment]
Hello, how did you fix it?
