### ISSUE TITLE
Canvas Data > Cast Shadows is sometimes ignored - Exporter 2.21.1-pre

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#56]
Able to repro this with the recently wetransfer sent project about lights being too bright, in some instances the Canvas Data is totally ignored when resaving the scene and now I have an instance where the Canvas UI is always casting shadows despite the Canvas Data being set to Cast Shadows 'off'

![image](https://user-images.githubusercontent.com/10745594/190178206-f5375ab1-1e93-4240-b9a7-c1a61c45c4c4.png)

**Comment by marwie** [comment]
Hey does this still reproduce?

**Comment by ROBYER1** [comment]
Is fixed recently
