### ISSUE TITLE
Broken/distorted skybox on export

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#59]
Using Unity 2022.1.16f1, Exporter 2.23.0-pre

I have sent a repro scene across, this project was upgraded from 2020.3.38f1

In Editor:
![image](https://user-images.githubusercontent.com/10745594/191291938-b081619e-2f96-44c3-917a-81f51fd2de2a.png)

In Build:
![image](https://user-images.githubusercontent.com/10745594/191291584-3bd2d48c-87c5-4555-898f-0c270654f761.png)

**Comment by marwie** [comment]
Can you try re-exporting your scene? This is a known issue with skybox export where it exports a broken skybox sometimes

**Comment by ROBYER1** [comment]
Seems to happen to me in production builds also - I do a Full Export and Build which looks fine but then using Needle Engine > Export and Build Dist (Production brings the borked skybox back :( )

**Comment by marwie** [comment]
It's unrelated to that and happens randomly unfortunately. As a workaround you can do the following:

![image](https://user-images.githubusercontent.com/5083203/193260937-7125544c-68ef-48a0-b37c-5d0ad0f21442.png)

and then

![image](https://user-images.githubusercontent.com/5083203/193260965-882e04b1-f823-45eb-a312-7e23e4e56c6b.png)

**Comment by marwie** [comment]
This should be fixed in 2.31.0-pre
