### ISSUE TITLE
Clean Export Error - System.IO.DirectoryNotFoundException: Could not find a part of the path 'Projects/newProject/cache~'.

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#61]
Windows 11, using Unity 2022.1.16f1, Exporter 2.23.0-pre

Holding alt to do a clean Export on the Exporter component gives me this error, happens in the repro project I sent for issues #59 and #60
```
DirectoryNotFoundException: Could not find a part of the path 'C:\Unity_Projects\projname\Projects\newProject\cache~'.
—
System.IO.DirectoryNotFoundException: Could not find a part of the path 'Projects/newProject/cache~'.

```

Could be worth checking if it exists or not to prevent this error blocking a full clean export

**Comment by marwie** [comment]
Thanks for the report, fixed for the next update :)
