### ISSUE TITLE
Unlit material with Transparency set exports as invisible

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#62]
See screenshot below, have sent a repro for this

![image](https://user-images.githubusercontent.com/10745594/191540617-d0a3e06c-24d9-4b96-ae80-813fd4c4359b.png)

**Comment by hybridherbst** [comment]
Can you please UnityGltf/PBRGraph and check with that?
Also, are you on 2021.3+ or on an earlier version?

**Comment by ROBYER1** [comment]
Also happening with a lit material, I'll send another repro to @marwie
