### ISSUE TITLE
GameObjects that are inactive on export or immediately set inactive in awake don't receive shadows

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#64]
Exporter 2.24.1-pre, Unity 2022.1.16f1

Make a scene with a directional light, something to case a shadow like a cube and a few planes with different materials, set the planes all inactive except one and make a button or way to set them active via code using GameObject.setActive. See that only the first plane that was active on export receives shadows.

The same happens if you leave all the planes active but in code set them all inactive in awake(). Works fine if you use start() instead.

**Comment by marwie** [comment]
Hey can not really reproduce here

https://user-images.githubusercontent.com/5083203/192378949-ff50403b-a225-4470-aeca-4eca319a2dad.mp4

**Comment by ROBYER1** [comment]
Going to close this now as the repro project isn't around but will remember to reopen if I see this again
