### ISSUE TITLE
Unable to deploy to Glitch with Build & Deploy: Prod using 2.24.1-Pre Exporter

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#65]
I have sent a repro for this, this project runs fine on local server but the glitch deployment to prod produces lots of errors on scripts that usually worked fine like 

```
src/scripts/ChangeSkybox.ts(7,36): error TS2339: Property 'material' does not exist on type 'GameObject'.
Open C:\Unity_Projects\Projname\Projects\newProject/src/scripts/ChangeSkybox.ts

```

Have sent over a repro and logs

**Comment by marwie** [comment]
Hey this reads like a error in your typescript code that blocks export. 

The type ``GameObject`` has no material property. So your code does something like ``this.gameObject.material`` it's actually an error. You need to check if ``material`` exists on the object. I would recommend you to not do that directory but instead query the ``Renderer`` component and set/update materials throught that.

For example

```ts
const rend = this.gameObject.getComponent(Renderer);
if(rend) rend.material = myMat;
```

**Comment by marwie** [comment]
You can modify how strict typescript is when building your project in the ``tsconfig.json``. 
Please read about that here: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by ROBYER1** [comment]
This was a job for the trusty old `//@ts-ignore` in cases where I couldn't resolve the errors for typescript on code that was working fine :)
