### ISSUE TITLE
error: Texture compression failed with 2.24.1-pre Exporter

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#66]
Exporter 2.24.1-pre, Unity 2022.1.16f1

Have sent a repro, try Build & Deploy: Prod on the Deploy To Glitch Component. Some very simple UI and textures in a small scene causing this issue

![image](https://user-images.githubusercontent.com/10745594/191767081-bb41e054-4c9e-4f63-8ccf-8e7b50de9e14.png)

**Comment by marwie** [comment]
Hey, currently we only support toktx version 4.0. You're currently on ``v4.1.0-rc3``.

Please install the version via [this link](https://github.com/KhronosGroup/KTX-Software/releases/tag/v4.0.0)
See [getting started](https://github.com/needle-tools/needle-engine-support/blob/main/documentation/getting-started.md#install-these-tools-for-production-builds)

**Comment by ROBYER1** [comment]
That was it!
