### ISSUE TITLE
VS Workspace Button stopped working - logs attached - Tested with Exporter 2.25.1-pre

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#68]
Exporter 2.25.1-pre, Unity 2022.1.16f1

In a project I've been working on for a week, randomly the VS Workspace button has stopped working, I have attached logs here, I hit the button to open it like 8-9 times so the logs should have picked up that!
[newProject-09-26.zip](https://github.com/needle-tools/needle-engine-support/files/9644851/newProject-09-26.zip)

**Comment by marwie** [comment]
Hey, logs dont say anything unfortunately and I can not reproduce here.
Do you think you could add a breakpoint in ``ExportInfoEditor`` in line ~271 where it tries to get the workspace path and show me what the path is in the ``workspacePath`` variable?

**Comment by ROBYER1** [comment]
Miraculously now works in a problematic project since updating, closing for now

**Comment by marwie** [comment]
Great to hear - I changed one thing in the path when opening the workspace, maybe that was causing the problem for you (ensuring it would open it with an absolute path instead of maybe relative)
