### ISSUE TITLE
Exported 3D > TextMeshPro text is not smooth in browser

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#70]
Exporter 2.25.1-pre, Unity 2022.1.16f1

See screenshot below, create a 3D > TextMeshPro Text and export to see this

![image](https://user-images.githubusercontent.com/10745594/192304936-3175bc57-4509-4669-af36-23b3a09673f5.png)

**Comment by hybridherbst** [comment]
Hey Rob, that's a UnityGltf issue for an experimental feature - these are meshes with textures, not interactive text components.

Please open an issue at
https://github.com/prefrontalcortex/UnityGLTF/issues

and use UI Text for Needle Engine. Thanks!
