### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'node_modules/three/examples/jsm/objects/GroundProjectedEnv.js'

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#75]
Using Unity 2022.1.16f1, updated to Exporter 2.26.0-pre

Hitting play gives me this now, needing to roll back a version now

```
(this will be run only when your dependencies or config have changed)
error when starting dev server:
Error: ENOENT: no such file or directory, open 'C:/Unity_Projects/ProjName/Projects/newProject/node_modules/three/examples/jsm/objects/GroundProjectedEnv.js'
    at Object.openSync (node:fs:594:3)
    at Object.readFileSync (node:fs:462:35)
    at optimizeDeps (C:\Unity_Projects\ProjName\projects\newProject\node_modules\vite\dist\node\chunks\dep-3e244802.js:63021:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOptimize (C:\Unity_Projects\ProjName\projects\newProject\node_modules\vite\dist\node\chunks\dep-3e244802.js:66813:48)
    at async Server.httpServer.listen (C:\Unity_Projects\ProjName\projects\newProject\node_modules\vite\dist\node\chunks\dep-3e244802.js:66829:21)
```

**Comment by marwie** [comment]
Hey did installation run after updating?

**Comment by marwie** [comment]
Another thing that would be cool if you could check is if the installed three version is correct. 
I'm just seeing a wrong three version being installed in one of my projects while in the samples repository I updated yesterday it installed the correct version (and I was able to run and build a sample using groundprojection there without problems)

would be great if you could send a screenshot of the content of the package json here:
![image](https://user-images.githubusercontent.com/5083203/192994412-09c2c1c0-64ef-4776-9b1b-698202d9b968.png)

**Comment by marwie** [comment]
Thank you!
yes that's the wrong version too there. It doesnt contain the GroundProjection. 
So it is the same problem I have here right now. Trying to figure out why it doesnt install the new three branch

**Comment by marwie** [comment]
Can you try updating to ``2.27.1-pre`` and see if it is fixed there? It should run ``npm update three`` automatically and after that have the correct version

**Comment by ROBYER1** [comment]
> Can you try updating to `2.27.1-pre` and see if it is fixed there? It should run `npm update three` automatically and after that have the correct version

Updated to that, still got the same error after an install...

**Comment by ROBYER1** [comment]
Trying the next pre.1 one

**Comment by marwie** [comment]
Did you see a log in the console saying it would run ``npm update`` ?
Could you try restarting Unity after updating if you dont?

**Comment by ROBYER1** [comment]
Exporter 2.27.1-pre.1 fixes this

**Comment by marwie** [comment]
Thanks
