### ISSUE TITLE
ERROR: Library/PackageCache/com.needle.engine-exporter@2.27.1-pre/Common/Runtime/Utils/ProcessHelper.cs(232,4): error CS0103: The name 'noWindow' does not exist in the current context

### ISSUE THREAD

**Issue by enslaved2die** [needle-tools/needle-engine-support#76]
I updated to the newest Version and I get this Error now.
I'm running a Macbook Pro M1 Pro on macOS 12.6

**Comment by hybridherbst** [comment]
Hey, which Unity version are you on?

**Comment by marwie** [comment]
Oh sorry - will be fixed in the next update

**Comment by marwie** [comment]
@enslaved2die can you try ``2.27.1-pre.1`` ?

**Comment by enslaved2die** [comment]
> Hey, which Unity version are you on?

2022.2.0b08

**Comment by enslaved2die** [comment]
> @enslaved2die can you try `2.27.1-pre.1` ?

Fixed! That was fast 😅
