### ISSUE TITLE
Directional Light shadow bias is not influenced by URP Render Settings or Directional Light > Shadow Bias > Custom Values

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#77]
Using Unity 2022.1.16f1, updated to Exporter 2.26.0-pre#

Setting these values in the editor in URP Render Settings or Directional Light > Shadow Bias > Custom Values do not influence the shadow bias of the directional light (s) in the scene. I have found using this script on a Directional Light will change the values appropriately:

```
import { Behaviour, GameObject } from "@needle-tools/engine/engine-components/Component";
import { serializeable } from "@needle-tools/engine/engine/engine_serialization_decorator";
import { Light } from "@needle-tools/engine";

export class LightFixer extends Behaviour
{
    @serializeable(Light)
    mainLight: Light;

    start(){
      console.log("light: " + this.mainLight["light"]);
      this.mainLight["light"].shadow.needsUpdate = true;
      this.mainLight["light"].shadow.bias = 0.0001;
      this.mainLight["light"].shadow.normalBias = 0.3;
      console.log(this.mainLight["light"].shadow.bias)
      console.log(this.mainLight["light"].shadow.normalBias);
           }
}
```

**Comment by marwie** [comment]
Thanks, can repro here. It was only exported when ``AdditionalLightData`` component is also on the gameobject since that holds the info for where to get the bias from.

**Comment by marwie** [comment]
On the light setting the Bias source to custom is exported and applied tho.

![image](https://user-images.githubusercontent.com/5083203/193070010-1fb817c2-0bd5-4f7a-94c7-ac687f24f3a7.png)


only when ``AdditionalLightData`` is missing (from URP) I'm not sure how to find what is set here:

![image](https://user-images.githubusercontent.com/5083203/193070167-910581ed-a53f-4dc9-bb88-a0e09170eaec.png)

in which case the setting from the Light is used which is not updated by the PipelineAsset so it exports a wrong value there

**Comment by ROBYER1** [comment]
I was having no results with Custom, I'll stick to using my script 😅 The project I sent via WeTransfer earlier is a good repro if you remove the Directional Light Fixer script on the Directional Light.

**Comment by marwie** [comment]
Hey Rob, just looked into this again. So the settings are exported as expected but internally it was doing a hacky multiplication which modified the values so they were unuseable - removing this for the next update

**Comment by marwie** [comment]
This has been removed in the latest version. Would be great if you could try again :)
