### ISSUE TITLE
Spatial Triggers do not scale for AR in Web AR Session Root

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#78]
Using Unity 2022.1.16f1, updated to Exporter 2.27.2-pre

Make a scene with Spatial Triggers around, deploy it to Desktop and AR, see that in AR the volumes are not scaled.

Some kind of helpers enabler for this could help for build debugging?

**Comment by marwie** [comment]
With helpers you mean visualization? You can add a ``BoxGizmo`` component and either disable ``isGizmo`` on it or open your webpage with a url query parameter: ``?gizmos``

**Comment by ROBYER1** [comment]
That's perfect I'll use that

**Comment by marwie** [comment]
First debugging results: 
Looks like spatial triggers get scaled correctly but the spatial trigger receiver attached to the camera has a wrong scale and causes unexpected intersections
