### ISSUE TITLE
[Exporter 2.9.5-pre] After updating package, failed to resolve import "../../node_modules/@needle-tools/engine/engine-components/AlignmentConstraint.ts" from "src\generated\scripts.js". Does the file exist?

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#8]
In project: https://github.com/needle-tools/needle-engine-support.git

When I updated Exporter Package  from 2.9.4-pre.1 to 2.9.5-pre (on Windows), I got this error when trying to run:

`Failed to resolve import "../../node_modules/@needle-tools/engine/engine-components/AlignmentConstraint.ts" from "src\generated\scripts.js". Does the file exist?
`
In the server page in Chrome I get this:
![errorneedle](https://user-images.githubusercontent.com/10745594/186652534-b5eb6a2b-61dd-457b-a76e-245ce24bdfdd.jpg)

In Editor I get a lot of errors like these when trying to run install and then also using the fix button that appears after on the Export gameobject in the scene: 
![image](https://user-images.githubusercontent.com/10745594/186651957-0faab108-1045-4534-9bc3-094fecdd9b0e.png)

**Comment by ROBYER1** [comment]
This could be a complete dud as I rolled back to the previous exporter package version then forward again and it worked, maybe this can be closed but I wanted to document it. I didn't have the server running prior to updating the package either, I simply opened the project today and updated the package before doing anything then tried to hit Play which seemed to start all this.

**Comment by marwie** [comment]
Thanks for reporting. Can you let me know which node/npm version you have installed?

when running your project I got these warnings:

![image](https://user-images.githubusercontent.com/5083203/186666521-b07591eb-9942-4a90-9d7f-d42ff780d9ae.png)

**Comment by ROBYER1** [comment]
npm 6.14.14

node v14.17.5

**Comment by marwie** [comment]
Great, thanks
