### ISSUE TITLE
Errors "Building & Deploy:Prod" with "toktx" involved

### ISSUE THREAD

**Issue by rgsaura** [needle-tools/needle-engine-support#80]
<img width="1032" alt="Unity_2dJhd43psM" src="https://user-images.githubusercontent.com/16281075/193422014-b9aa4457-d983-43c5-83df-b5b510f4f218.png">

I tried to install "toktx" path multiple times and restarted the computer. It shows this error when "installing to path"
<img width="374" alt="KTX-Software-4 0 0-win64_U7zZZkb4QX" src="https://user-images.githubusercontent.com/16281075/193422194-3f93740f-8741-47d3-85ef-1a6145cb1f46.png">

**Comment by rgsaura** [comment]
> Hello, did you change the default toktx installer location?
> 
> Please make sure to install the correct version linked here too: https://github.com/needle-tools/needle-engine-support/blob/main/documentation/getting-started.md#install-these-tools-for-production-builds

Yes, I installed the version you provide, this is what the installation looks like

![Unity_Hub_qZRsdegJVn](https://user-images.githubusercontent.com/16281075/193422364-9f35e816-ea4a-4f65-8231-1ba89b7bd7b5.gif)

**Comment by rgsaura** [comment]
> > Hello, did you change the default toktx installer location?
> > Please make sure to install the correct version linked here too: https://github.com/needle-tools/needle-engine-support/blob/main/documentation/getting-started.md#install-these-tools-for-production-builds
> 
> Yes, I installed the version you provide, this is what the installation looks like
> 
> ![Unity_Hub_qZRsdegJVn](https://user-images.githubusercontent.com/16281075/193422364-9f35e816-ea4a-4f65-8231-1ba89b7bd7b5.gif) [ ![Unity_Hub_qZRsdegJVn](https://user-images.githubusercontent.com/16281075/193422364-9f35e816-ea4a-4f65-8231-1ba89b7bd7b5.gif) ](https://user-images.githubusercontent.com/16281075/193422364-9f35e816-ea4a-4f65-8231-1ba89b7bd7b5.gif) [ ](https://user-images.githubusercontent.com/16281075/193422364-9f35e816-ea4a-4f65-8231-1ba89b7bd7b5.gif)

If I dont add to path the error when building stays the same :/

**Comment by marwie** [comment]
When you dont add it to the path toktx can not be found by windows / the application - that's why the build fails.

Did you change the installation location? The error you are seeing is a windows error/limitation I think (max path length is 260 chars). Not sure why you hit that tho

**Comment by marwie** [comment]
That being said: you can produce builds without toktx installed (toktx is used for compressing the images and reduces the size of your final glb files drastically - but it is not a hard requirement). For that just go to the Unity BuildSettings window and tick the ``Development Build`` checkbox

![image](https://user-images.githubusercontent.com/5083203/193423012-e226a44a-a867-465c-a7ae-53553222bd66.png)

**Comment by rgsaura** [comment]
@marwie The point of the gif was to show that Im not modifying the installation path. I looked for solutions for the "long path problem" but even with a registry option to enable them is still not working.

Thanks fo the "temporal solution". Hopefully I´ll try again in the future and it works somehow

I´ll update. 😄

**Comment by marwie** [comment]
Maybe you can raise an issue in the [toktx repository](https://github.com/KhronosGroup/KTX-Software) too as I'm not sure why their installer fails for you unfortunately :(

**Comment by hybridherbst** [comment]
Hey, this is unfortunately a known issue with the toktx installer not adding to PATH in some cases:
- https://github.com/KhronosGroup/KTX-Software/issues/244

For now you'll have to manually add it there if that happens.

@marwie might make sense if we check if it's in the default installation directory and work around that issue on our end; have seen it happen a couple times now.

**Comment by rgsaura** [comment]
Okey, so after setting the toktx to the variables path & restarting the pc it works when I deploy on Production.
One consequence of this though its the strange display of my sky box.

![brave_l6ovE3M7Zg](https://user-images.githubusercontent.com/16281075/193427582-9ef36013-e830-4775-91ef-a456be71bcd4.gif)

**Comment by marwie** [comment]
Hey, this is a known issue and unrelated to toktx.  https://github.com/needle-tools/needle-engine-support/issues/59

When it happens exporting the scene again helps usually.

**Comment by rgsaura** [comment]
Awesome! thanks for the help! @marwie & @hybridherbst

**Comment by enginetla** [comment]
> 

Good afternoon! Tell me, how did you add toktx to Unity? Do I understand correctly, are you using toktx to convert textures to runtime?
