### ISSUE TITLE
Mozilla WebXR viewer - Using Bike demo, the X button to close AR and bottom UI don't show - Dom overlay support?

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#81]
Using the bike demo from here https://needle-bike.glitch.me/

On IOS the X button in AR doesn't show and the bottom UI to change bike colour/animations doesn't show. Works fine on Android Chrome. Could be related to dom overlay according to Felix?

Screenshots:
![IMG_0026](https://user-images.githubusercontent.com/10745594/193794268-39d5311b-fea5-4f4e-9541-60920e783bbf.PNG)

![Screenshot_20221004-105755](https://user-images.githubusercontent.com/10745594/193794262-89130727-809e-4d88-bdc1-39152356d400.png)

Discord post: https://discord.com/channels/717429793926283276/1026797313080950816 

Using Unity 2022.1.17f1 and Needle Exporter 2.24.0-pre with the Bike Configurator (I assume).

**Comment by marwie** [comment]
Does this happen consistently?

If not it could also be related to the X generally sometimes not showing up - can you try if you press at roughly top right corner if you exit XR even tho the button is not visible? Sometimes the X is not rendered but can be clicked

**Comment by ROBYER1** [comment]
> Does this happen consistently?
> 
> If not it could also be related to the X generally sometimes not showing up - can you try if you press at roughly top right corner if you exit XR even tho the button is not visible? I sometimes had an issue where the X is not rendered but can be clicked (so the div is actually there)

Happens consistently using iphone 6 with Mozilla WebXR viewer, the UI for AR doesn't show at all, notice in the screenshots that the bottom panel with bike options doesn't show. Tapping where the UI would be does nothing. ALso the browser back button doesn't activate to take you back out of AR, it stays greyed out as if we haven't changed webpage/areas to get to AR as far as Mozilla WebXR viewer sees it so the user is stuck in AR.

**Comment by marwie** [comment]
Hello @ROBYER1 this should work in 2.48.0-pre, would be great if you could verify

**Comment by ROBYER1** [comment]
> Hello @ROBYER1 this should work in 2.48.0-pre, would be great if you could verify

Testing this against the bike configurator repo, will report back shortly

**Comment by marwie** [comment]
> Testing this against the bike configurator repo, will report back shortly

The bike configurator website has not yet been updated

**Comment by ROBYER1** [comment]
I have access to the Needle Repo for it with the source so I'm testing there, not the live site

**Comment by hybridherbst** [comment]
Can you test in our sample scene? 
The bike hasn't been updaetd in a while and may have other unrelated changes that are needed.

**Comment by ROBYER1** [comment]
Tested with the normal Needle Engine Starter scene in AR and on Android the top right 'X' to close AR shows while on IOS Mozilla WebXR Viewer the 'X' button doesn't show in AR.

IOS iPhone 6 Mozilla WebXR Viewer:
![IMG_0037](https://user-images.githubusercontent.com/10745594/203574772-be5134e8-6fd9-48ae-9767-4649811144b0.PNG)

Android Xperia 1 Chrome:
![Screenshot_20221123-144007](https://user-images.githubusercontent.com/10745594/203575215-5b7588fd-34fe-4635-8782-bbb21dc5620c.png)

**Comment by marwie** [comment]
The screenshot look like an old version too (thats the old starter we used before beta)? How did you create that scene?

**Comment by ROBYER1** [comment]
> The screenshot looks like an old version too (thats the old starter we used before beta)? How did you create that scene? Is that scene still somehwere in the package? 🤔

I used this scene, is there another scene/repo I should test with? https://github.com/needle-tools/needle-engine-support/blob/main/starter/Needle%20Engine%20Starter%202020_3/Assets/Scenes/Basic.unity

**Comment by marwie** [comment]
Yes sorry for the confusion - removed the old project now to avoid it being used in the future

**Comment by ROBYER1** [comment]
Using the HTML AR Overlay sample scene, the DOM overlay stuff worked perfectly, obviously pressing X on IOS causes a white screen which is a known issue.

However, testing using Collaborative Sandbox sample scene produced the same issue of the 'x' on the top right not showing on iOS and the placement circle didn't show on iOS. On Android Chrome both the placement circle and X icon showed fine.

**Comment by marwie** [comment]
Thanks for testing again! Will check why that is

**Comment by marwie** [comment]
Next version should fix this as well as the white screen

**Comment by marwie** [comment]
Thanks for testing. 

Not sure if that avatar behaviour is new but its not related to MozillaXR - would close this issue then and track the avatar in another one

**Comment by ROBYER1** [comment]
Shall I make a separate issue for the shadow acne on mobile issue also?

**Comment by marwie** [comment]
Is that mobile only? I created a new template here and tried on mozilla: dont see it https://rust-working-juniper.glitch.me
How did you create the scene? Do you have additional shadow settings there?

That's how the light looks for me
![image](https://user-images.githubusercontent.com/5083203/203785931-8e5994fa-585f-4833-aae4-208e80595e3e.png)

**Comment by marwie** [comment]
@ROBYER1 btw for debugging on mobile you can now use the new ``?console`` parameter

**Comment by ROBYER1** [comment]
> Is that mobile only? I created a new template here and tried on mozilla: dont see it https://rust-working-juniper.glitch.me
> 
> How did you create the scene? Do you have additional shadow settings there?
> 
> That's how the light looks for me ![image](https://user-images.githubusercontent.com/5083203/203785931-8e5994fa-585f-4833-aae4-208e80595e3e.png)

Mobile only, it is the collaborative sandbox sample built untouched by me and running on Mozilla WebXR Viewer IOS on iPhone 6, the shadow issue doesn't occur on desktop. I'll test it on android after lunch.

**Comment by marwie** [comment]
Which RP and Editor version are you using? It doesnt reproduce on 2020.3.33 using URP here, just re-uploaded a brand new template scene https://rust-working-juniper.glitch.me/

**Comment by ROBYER1** [comment]
I opened an issue here with the source project just in case and more info, might just be one to write off as iPhone 6 is pretty much outdated and if it doesn't repro on a newer iPhone like the S then we can probably just ignore it.

https://github.com/needle-tools/needle-engine-support/issues/116

**Comment by ROBYER1** [comment]
@marwie Can we reopen this issue as this reproduces with Needle Exporter 2.66.1-pre as a regression across all of my projects, repro project: https://drive.google.com/file/d/1O4HjKuo72IC6hc2hc6WavkLYOhgj-0QH/view?usp=share_link

You can even see in the gif here of the bike demo that the X button does not show on the top right so we are trapped in AR
https://discord.com/channels/717429793926283276/1085901956507246662/1085901956507246662

**Comment by hybridherbst** [comment]
Just to clarify @ROBYER1 you're referring to Mozilla's viewer on iOS? We've been doing quite a bit of AR lately and the X shows on Android WebXR. Does it show for you on Android devices?

**Comment by ROBYER1** [comment]
> Just to clarify @ROBYER1 you're referring to Mozilla's viewer on iOS? We've been doing quite a bit of AR lately and the X shows on Android WebXR. Does it show for you on Android devices?

This bug is specific to IOS Mozilla WebXR viewer where the X to close AR does not show as you can see here 
https://cdn.discordapp.com/attachments/1085901956507246662/1085901956842795038/BikeDemoOffline.gif

On Android Chrome the X to close AR always shows and works fine, this issue is only on IOS Mozilla WebXR Viewer

**Comment by ROBYER1** [comment]
What makes this weirder is that on some initial runs on iOS Mozilla WebXR, the X button doesn't show but on subsequent local server refreshes it eventually shows up at some point then always shows until I restart my laptop and iOS device
