### ISSUE TITLE
Exporter 2.30.1-pre - Error with Prefabs exported using a canvas in animation - not found .nodes.CanvasParent 

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#83]
Exporter 2.30.1-pre, Unity 2022.1.16f1, Windows 11

Was working fine to export gameobjects that had animations on them that referenced a canvas which was a child of them (although the animation for the canvas didn't export). This update seems to make those gameobjects not export and I get the following error:

```
error_overlay.ts:25 not found .nodes.PlaneText Object3D {isObject3D: true, uuid: '7e99e3ab-3513-49d6-96fd-e3b645969442', name: 'Hotspot10-Connect-Sheet', type: 'Object3D', parent: Object3D, …} Hotspot10-Connect-Sheet 
```

Will send over a repro as this one is difficult to explain

**Comment by marwie** [comment]
2.31.0-pre should fix this
