### ISSUE TITLE
Canvas doesn't fully reappear when set GameObject.Active() true/false

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#84]
Unity 2022.1.16f1, Exporter 2.30.0-pre

Repro sent, using this very simple script below to show/hide canvas gameobjects, they don't full re-show as in an X button is missing and they aren't interactive anymore

In logs is erros:

```
THREE.PropertyBinding: Trying to update property for track: .nodes.CanvasParent.activeSelf but it wasn't found.
```

Before:
![image](https://user-images.githubusercontent.com/10745594/194362616-ce6caf8b-ba99-43f7-9b6f-f5048b982c6d.png)

After:
![image](https://user-images.githubusercontent.com/10745594/194362567-7c7f82d7-09b2-4aa1-9293-be4ff0cf0379.png)

```
import { Behaviour, GameObject } from "@needle-tools/engine/engine-components/Component";
import { serializeable } from "@needle-tools/engine/engine/engine_serialization_decorator";
import { Light } from "@needle-tools/engine";

export class ReproCanvasBug extends Behaviour
{
    @serializeable(GameObject)
    public panel?: GameObject[];

    start(){
        //Try commenting out this start section to see that the X on the canvas doesn't show
            for (let i = 0; i < this.panel.length; i++) 
            {
                //GameObject.setActive(this.panel[i], false);
            }
           }
        
           public ActiveHotspot(currHotspot: number)
           {
                for (let i = 0; i < this.panel.length; i++) 
                {
                    GameObject.setActive(this.panel[i], false);
                }
               GameObject.setActive(this.panel[currHotspot], true);
           }

           public InActiveHotspot(currHotspot: number)
           {
               GameObject.setActive(this.panel[currHotspot], false);
           }
}
```

**Comment by ROBYER1** [comment]
I think the error is the main  root cause but try uncommenting out the hide all in start function then add `GameObject.setActive(this.panel[1], true);` or something to see when they re-show it glitches out

**Comment by marwie** [comment]
Please try if 2.31.0-pre fixes this!

**Comment by hybridherbst** [comment]
Needs to be investigated again it seems, multiple reports:
https://discord.com/channels/717429793926283276/1075093865830285433

**Comment by marwie** [comment]
Does reproduce here

**Comment by marwie** [comment]
Should be fixed in the next update
