### ISSUE TITLE
UI Buttons don't respond to clicks always in export

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#86]
Unity 2022.1.16f1, Exporter 2.32.0-pre

@marwie Please use the Zipped project I sent you today to repro this.

Scene has hotspots and when one is pressed, a panel opens which has a canvas that is opened by setting it active in code. The 'X' button on that canvas doesn't always respond to clicks.

I think it could be a scaling issue on export as the buttons only work if I click right in the middle of the X and not the outside

**Comment by ROBYER1** [comment]
Minimal repro - you will see in SceneRoot - Content - Camera 1 - PanelTarget - ProductPanel (20) if you enable or disable the Animator component, it causes the UI Text to render/not render.

The UI Text rendering/not rendering also seems connected to the buttons being interactive only in their very center - if the text is not rendering + animator component on, only the very middle of the button clicks, otherwise if the animator is off + text renders, the button clicks from anywhere on the button
![unknown (2)](https://user-images.githubusercontent.com/10745594/195071194-527af9a4-6148-4690-a6a8-f77552a8608f.png)

I must stress that in my larger main project, the text DOES render while the animator is on and I can send that larger project, but the underlying issue of only the center of the button working for clicks is the real issue there.

[newProject-221011_uw.zip](https://github.com/needle-tools/needle-engine-support/files/9754314/newProject-221011_uw.zip)

**Comment by ROBYER1** [comment]
Was caused by text overlapping the button but unticking Raycast target on text didn't fix, moving button higher fixed it. Raycast Target not exporting is a known thing.

**Comment by marwie** [comment]
Next version will support ``raycastTarget`` option on UI Graphic components (e.g. Text)
