### ISSUE TITLE
Opening a new project while another one was open causes play button to not work

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#87]
Unity 2022.1.16f1, Exporter 2.32.0-pre, Windows 11

Logs exported from an instance where the play button stays as refresh, no errors in logs but nothing ever opens in Chrome and the refresh icon doesn't change to the play icon. I hit the play button like 5-6 times.

I had another project open that I closed the chrome tab and terminal that was showing the vite stuff running - but left Unity open
Exported that project as a zip to make a repro for a bug
Kept the old project open in unity but opened the new zipped one
Tried hitting play loads of times in the newly opened one but nothing happened 

To finally get it running, I closed the old project in Unity (got an error about a process not being able to exit), then opened Task Manager and repeatedly stopped the node.ex eand node runtime processes (even though node .exe would fire back up everytime after I did that). After spam closing them in Task Manager, I went back to the new Unity project and the Play button on Export Info changed from refresh to play icon.
[newProject-221007.zip](https://github.com/needle-tools/needle-engine-support/files/9733395/newProject-221007.zip)

**Comment by ROBYER1** [comment]
[newProject-221010.zip](https://github.com/needle-tools/needle-engine-support/files/9744766/newProject-221010.zip)
More logs from another time this happened, left old project Unity Editor open and newly opened project simply won't play.

**Comment by marwie** [comment]
Hey I've been testing this extensively yesterday and today. It opens the new server reliably for me in 2.35.3-pre. Would be great if you could try again on your end and let me know if it is still a problem

**Comment by ROBYER1** [comment]
Can work around this well using Needle Engine > Stop Server on the other project first.
