### ISSUE TITLE
Enabled events only fire when using 'onEnable()' but component enable/disable is only working with 'OnEnable()'

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#93]
With the 'OnEnable()' function, it only shows the inspector Component tickbox for Enable/Disable when using 'OnEnable()', but the enabled event won't fire unless we use 'onEnable()' in the script, is there a reason the naming is different? I assume this is the same with the disable events.

```
import { serializeable } from "@needle-tools/engine";
import { Behaviour, GameObject } from "@needle-tools/engine/engine-components/Component";

export class ZoneForwarder extends Behaviour
{


    start()
    {
        console.log("started");
    }

    OnEnable ()
    {
        console.log("enabled");
    }

    
    onEnable ()
    {
        console.log("other enabled");
    }

}
```

**Comment by marwie** [comment]
Yes its for consistency in the typescript codebase where all methods are in lowerCamelCase and the OnEnable / OnDisable methods are Unity specific and **just** for the tickbox to show up. We've talked about adding a special case maybe to codegen to emit a ``OnEnable`` method in Unity for ``onEnable`` in typescript but that's not implemented yet.

**Comment by ROBYER1** [comment]
Makes sense to me!

**Comment by marwie** [comment]
Component compiler 1.9.0 will emit ``onEnable`` as ``OnEnable`` and ``onDisable`` as ``OnDisable``
Will bump the dependency in the runtime engine

For code in ``src/scripts`` the ComponentGenerator component should also pickup the updated version and display it in the footer of the component

![image](https://user-images.githubusercontent.com/5083203/196447006-dcf3f154-89c9-45d9-871f-9cae5446ce42.png)
