### ISSUE TITLE
Exporter 2.33.0-pre intermittently asks to run project setup after changing scripts/saving scenes 

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#94]
Was not doing this in 2.32.0-pre, using Unity 2022.1.16f1 in Windows 11

After upgrading in a project I sent a few repros with in the past, I was running the server then changing some scripts, saving the scene and sometimes toggling on/off on the component generator when sometimes a script didn't update

Logs
[newProject-221011.zip](https://github.com/needle-tools/needle-engine-support/files/9753355/newProject-221011.zip)

**Comment by marwie** [comment]
Hello @ROBYER1 sorry im not quite sure what you mean here? The setup engine button shows up repeatedly for some reason after changing scripts?
