### ISSUE TITLE
Exported fonts have letters space out very far apart vs Unity UI Text use of the font

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#95]
See screenshot below, affects 2.32.0-pre and above, using Unity 2022.1.16f1

Left is Unity Editor, right is Needle Export
![image](https://user-images.githubusercontent.com/10745594/195051012-95787ce4-8140-4508-ac41-17e1d763bea0.png)

Font:
[Saira_Condensed-SemiBold.zip](https://github.com/needle-tools/needle-engine-support/files/9753558/Saira_Condensed-SemiBold.zip)

**Comment by hybridherbst** [comment]
Related
- https://github.com/felixmariotto/three-mesh-ui/issues/161

**Comment by marwie** [comment]
![image](https://user-images.githubusercontent.com/5083203/196386174-41b1e25e-f367-46cc-9dc3-2310fdd80e5d.png)

kernings array is empty in loaded font family

**Comment by marwie** [comment]
Will have a look at that in a bit

**Comment by ROBYER1** [comment]
Could be useful to have some override or fallback if the kerning array is empty as a default, if it isn't empty it can be overwritten.

**Comment by marwie** [comment]
So kerning data is loaded when available - seems like this is not generated/available for every font
https://github.com/soimy/msdf-bmfont-xml

![image](https://user-images.githubusercontent.com/5083203/196422018-b6806fd4-f38f-4891-af5a-cf693403a54b.png)

**Comment by marwie** [comment]
Hello @ROBYER1 do you still have this issue?
