### ISSUE TITLE
Vite React - Generating new project always says 'Directory Not Empty' when using an empty new folder on Windows 11

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#96]
Unity 2022.1.16f1, Exporter 2.32.0-pre

Made new scene > Export object > Export component > Picked folder, made brand new empty folder in 'projects' folder, picked Vite React, clicked generate then get the error 'Directory Not Empty'. Folder does appear to contain generated project 

1. Make new scene
2. Add Export gameobject
3. Clicking Pick, making a folder new to generate the project in
4. The Project Folder input field autofills projects/BrandNewFolder/React
5. I click Generate Project
6. Get error, project seems to be generated in the folder I chose under 'React'

![image](https://user-images.githubusercontent.com/10745594/195077195-0dc7fbd6-0fbd-4b6c-b69b-92106df9667f.png)

![](https://cdn.discordapp.com/attachments/1029348622111870976/1029351675338686564/unknown.png)

![](https://cdn.discordapp.com/attachments/1029348622111870976/1029351739243122788/unknown.png)

**Comment by marwie** [comment]
This issue was caused by falsely specifiying the Unity Assets folder as a *Project template*
