### ISSUE TITLE
Black screen in Local Server with 2.39.1-pre, no errors in log

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/needle-engine-support#99]
Using exporter 2.39.1-pre is giving me black screens on Local Server playing, I can send a repro. Project works fine if I roll back to 2.38.1-pre and I have tried a clean install + Full export each time.

Try with this project.
[newProject-221024_uw.zip](https://github.com/needle-tools/needle-engine-support/files/9851917/newProject-221024_uw.zip)

**Comment by marwie** [comment]
Sorry about that, it can be fixed by removing line 32 in the index.html

![image](https://user-images.githubusercontent.com/5083203/197536683-e51420f7-e0ea-41de-bd24-1c4957346f4e.png)
